ui/src/components/avatar/QasAvatar.stories.js
=> QasAvatar Documentation

ui/index.js, ui/src/components/copy/QasCopy.stories.js, ui/src/components/copy/QasCopy.vue, ui/src/index.js, ui/src/plugins/index.js
=> First version of QasCopy docs

ui/src/components/input/QasInput.stories.js, ui/src/components/input/QasInput.vue, ui/src/index.js
=> Input Documentation

ui/src/components/debugger/QasDebugger.stories.js, ui/src/components/debugger/QasDebugger.vue
=> Creating QasDebugger docs

ui/.babelrc, ui/package.json, ui/src/components/box/QasBox.spec.js
=> adjusts for test and implemented in QasBox

ui/src/components/password-input/QasPasswordInput.stories.js, ui/src/components/password-input/QasPasswordInput.vue, ui/src/components/password-strength-checker/QasPasswordStrengthChecker.vue, ui/src/index.js
=> Password Input Documentation

ui/jest-setup.js, ui/jest.config.json, ui/package-lock.json, ui/package.json, ui/src/components/apps-menu/QasAppsMenu.spec.js, ui/src/components/apps-menu/QasAppsMenu.vue
=> QasAppsMenu Test

ui/src/components/field/QasField.stories.js, ui/src/components/field/QasField.vue, ui/src/index.js
=> QasField Documentation

ui/src/components/form-generator/QasFormGenerator.stories.js, ui/src/components/form-generator/QasFormGenerator.vue, ui/src/index.js
=> FormGenerator Documentation

ui/.storybook/preview.js, ui/package-lock.json, ui/package.json, ui/src/components/filters/QasFilters.stories.js, ui/src/components/filters/QasFilters.vue, ui/src/mixins/context.js, ui/src/mocks/json/users-new.json, ui/src/mocks/storeModule.js
=> Filters Documentation

ui/src/components/decimal-input/QasDecimalInput.stories.js
=> Decimal-input Documentation

ui/src/components/resizer/QasResizer.stories.js, ui/src/components/resizer/QasResizer.vue, ui/src/helpers/greatestCommonDivisor.js, ui/src/helpers/index.js, ui/src/index.js
=> Resizer Documentation

CHANGELOG.md, app-extension/src/index.js, ui/src/asteroid.js, ui/src/helpers/filters.js, ui/src/helpers/index.js, ui/src/index.js, ui/src/mixins/index.js
=> mixins and others adjusts

CHANGELOG.md, ui/.eslintrc.js, ui/dev/package-lock.json, ui/dev/package.json, ui/dev/src/css/quasar.variables.scss, ui/dev/src/layouts/MainLayout.vue, ui/dev/src/pages/TestDesignSystem.vue, ui/dev/src/router/routes.js, ui/package-lock.json, ui/src/css/background.scss, ui/src/css/border-radius.scss, ui/src/css/design-system.scss, ui/src/css/shadow.scss, ui/src/index.scss
=> Background, border and gradients styles

CHANGELOG.md, ui/src/mixins/form.js, ui/src/mixins/index.js
=> added form mixin

CHANGELOG.md, ui/src/components/grid-generator/QasGridGenerator.vue
Adding array check on formattedFields
=> Adjust on QasGridGenerator when is array and is empty

CHANGELOG.md, ui/src/components/field/QasField.vue
=> Adjusting password hide strenght

CHANGELOG.md, ui/src/components/app-bar/QasAppBar.vue, ui/src/components/apps-menu/QasAppsMenu.vue
- Modifficação na estrutura do notifications (caso não tenha suporte para notificação não mostrar)
- Modificação nos espaçamentos do appsBar com o icone de notifications
=> AppBar Component changes

CHANGELOG.md, ui/src/components/box/QasBox.vue
Em conversa com o Lucas, houve essa pequena modificação no background quando não esta em um modo de formulário
=> qas-box background changes

CHANGELOG.md, ui/src/components/nested-fields/QasNestedFields.stories.js, ui/src/components/nested-fields/QasNestedFields.vue
=> nested fields changes

CHANGELOG.md, ui/src/components/delete/QasDelete.stories.js, ui/src/components/delete/QasDelete.vue
- Adicionando a prop para sobrescrever a url de deleção de alguma entidade
=> adding URL prop to QasDelete

CHANGELOG.md, ui/src/mixins/map-markers.js
Precisei fazer um Fix para a importação do icon do map, estava quebrando outras aplicações.
=> fixing map-markers icon import

CHANGELOG.md, ui/dev/src/pages/TestListItems.vue, ui/package-lock.json, ui/src/components/card/QasCard.vue, ui/src/components/list-items/QasListItems.stories.js, ui/src/components/list-items/QasListItems.vue, ui/src/index.js
- Added new component `QasListItems`.
=> Finished QasListItems

CHANGELOG.md, ui/src/components/filters/QasFilters.vue
Select filter multiple that came with an item in the URL broke the component
=> fix: Select multiple crashing with one item in URL

docs/src/assets/menu.js, docs/src/pages/composables/useHistory.md
Foi criado a documentação da composição **useHistory**
=> Documentação das composições 

docs/src/layouts/DocLayout.vue
Adicionado botão no header para menu lateral
=> Botão de Menu lateral

CHANGELOG.md, ui/src/components/filters/QasFilters.vue, ui/src/components/search-box/QasSearchBox.vue
Inclua uma pequena descrição explicando o motivo do pull request
=> finished changes for replacing q-input for qas-input

CHANGELOG.md, ui/dev/src/pages/users/UsersCreate.vue, ui/package-lock.json, ui/src/components/nested-fields/QasNestedFields.vue, ui/src/helpers/camelize-fields-name.js, ui/src/helpers/index.js, ui/src/mixins/view.js
Inclua uma pequena descrição explicando o motivo do pull request
=> created helper camlizeFieldsName

CHANGELOG.md, ui/package-lock.json, ui/src/components/actions-menu/QasActionsMenu.vue, ui/src/components/list-view/QasListView.vue, ui/src/components/signature-uploader/QasSignatureUploader.vue, ui/src/components/single-view/QasSingleView.vue
=> added params in fetchList/fetchSingle

CHANGELOG.md, docs/package-lock.json, docs/src/pages/components/uploader.md, ui/src/components/search-box/QasSearchBox.vue, ui/src/components/uploader/QasUploader.vue, ui/src/components/uploader/QasUploader.yml
=> QasUploader object model

CHANGELOG.md, app-extension/package-lock.json, app-extension/package.json, build/build.js, build/release/changelog-handler.js, build/release/create-github-release-from-browser.js, build/release/create-github-release.js, build/release/get-app-extension-package.js, build/release/get-latest-versions.js, build/release/get-nearest-version.js, build/release/get-normalized-versions.js, build/release/get-version-link-compare.js, build/release/git-handler.js, build/release/install-next-ui.js, build/release/notify-discord-chat.js, build/release/release-app-extension.js, build/release/release-ui.js, docs/package-lock.json, docs/package.json, package-lock.json, package.json, ui/package-lock.json, ui/package.json
- Criado automatização de todo processo de publicação do asteroid.
=> Feture/main homolog/automatic release

CHANGELOG.md, docs/package-lock.json, docs/package.json, docs/src/examples/QasInput/Masks.vue, ui/package-lock.json, ui/package.json, ui/src/components/input/QasInput.vue
- `quasar`: atualizado quasar para `2.10.1`.
- `QasInput`: corrigido problemas de mascara ao alterar valor do model fora do componente.
- [ x Fiz meu próprio _code review_ antes de abrir este _pull request_.
=> Fix mask in QasInput

docs/src/assets/menu.js, docs/src/examples/QasPagination/Basic.vue, docs/src/pages/components/pagination.md, ui/src/components/pagination/QasPagination.vue, ui/src/components/pagination/QasPagination.yml, ui/src/vue-plugin.js
Novo componente QasPagination.
=> QasPagination

CHANGELOG.md, docs/src/pages/components/list-view.md, ui/src/components/list-view/QasListView.vue, ui/src/components/table-generator/QasTableGenerator.vue
Adicionado `QasPagination` no `QasListView` e algumas alterações referentes a paginação.
=> feat(QasListView): Changes in pagination

.vscode/settings.json, CHANGELOG.md, ui/src/components/form-generator/QasFormGenerator.yml, ui/src/components/grid-generator/QasGridGenerator.yml, ui/src/mixins/generator.js
Foi alterado o valor do gutter com base no DS
=> feat(Mixins): changed gutter value

CHANGELOG.md, docs/src/examples/QasListView/CommonUsage.vue, docs/src/pages/components/list-view.md, ui/src/components/list-view/QasListView.vue, ui/src/components/list-view/QasListView.yml
=> Handle delete on QasListView

CHANGELOG.md, ui/src/components/list-view/QasListView.vue
https://app.clickup.com/t/3ehb04t
=> Changes empty results

CHANGELOG.md, ui/src/components/select/QasSelect.vue
Alterado posição do icone de busca do select para a esquerda.
clickup: https://app.clickup.com/t/864dhuj6a
=> Update search icon position on QasSelect

CHANGELOG.md, ui/src/components/form-view/QasFormView.vue, ui/src/components/form-view/QasFormView.yml
- `QasFormView`: alterado valor default da propriedade `cancelButtonLabel` de "Cancelar" para "Voltar".
clickup: https://app.clickup.com/t/864dhud5n
=> Changed default prop `cancelButtonLabel` from QasFormView

CHANGELOG.md, ui/src/components/form-view/QasFormView.vue
Agora os erros são resetados quando acontece o submit com sucesso.
clickup: https://app.clickup.com/t/864djccqk
=> Fix error on submit success on QasFormView

CHANGELOG.md, ui/src/components/app-menu/QasAppMenu.vue
- `QasAppMenu`: adicionado validação na badge de desenvolvimento.
clickup: ## Não publicado
- `QasAppMenu`: adicionado validação na badge de desenvolvimento.
=> Fix develop badge

CHANGELOG.md, docs/src/examples/QasAvatar/Title.vue, docs/src/pages/components/avatar.md, ui/src/components/app-menu/QasAppMenu.vue, ui/src/components/app-user/QasAppUser.vue, ui/src/components/avatar/QasAvatar.vue, ui/src/components/avatar/QasAvatar.yml
- `QasAvatar`: mudanças relacionadas a cor.
- `QasAvatar`: adicionado propriedade `size`.
- `QasAvatar`: adicionado propriedade color sendo possível passar 2 valores `primary` e `secondary-contrast`.
- QasAppMenu: adicionado `border-radius: 4px` no select de módulos.
- `QasAppUser`: corrigido avatar.
=> finished changes

CHANGELOG.md, ui/src/components/avatar/QasAvatar.vue
- `QasAvatar`: corrigido $attrs.
=> Fixed QasAvatar $attrs

CHANGELOG.md, app-extension/src/templates/css/quasar.variables.scss, docs/src/css/quasar.variables.scss, docs/src/pages/start/usage.md, ui/src/css/utils/index.scss, ui/src/css/utils/shadow.scss
- `shadow.scss`: modificado cor `shadow-2` do quasar.
- modificado cor `accent` para opacidade de `10%` ao invés de `20%`.
=> changes in shadow

CHANGELOG.md, ui/src/components/date-time-input/QasDateTimeInput.vue
- `QasDateTimeInput`: adicionado validações para datas invalidas.
=> Changed QasDateTimeInput

CHANGELOG.md, docs/src/examples/QasAppMenu/Basic.vue, ui/src/components/app-bar/QasAppBar.vue, ui/src/components/app-menu/QasAppMenu.vue, ui/src/components/app-user/QasAppUser.vue
- [`QasAppMenu`, `QasAppBar`, `QasAppUser`]: mudanças de layout.
clickup: https://app.clickup.com/t/864dm7wxt
=> Changes in QasAppMenu / QasAppBar / QasAppUser

CHANGELOG.md, docs/src/assets/menu.js, docs/src/examples/QasWelcome/Basic.vue, docs/src/pages/components/welcome.md, ui/src/components/welcome/QasWelcome.vue, ui/src/components/welcome/QasWelcome.yml, ui/src/components/welcome/private/PvWelcomeShortcutCard.vue, ui/src/shared/date-config.js, ui/src/vue-plugin.js
- `QasWelcome`: adicionado novo componente de boas-vindas para uso na Home.
- `date-config.js`: adicionado arquivo para configurações de datas.
=> Created QasWelcome

CHANGELOG.md, app-extension/src/boot/loading.js, ui/src/css/plugins/loading.scss
- [`loading.js`, `loading.scss`]: adicionado custom class `qas-loading` para só estilizar o loading quando existir esta classe.
=> Fix loading style

CHANGELOG.md, docs/package-lock.json, docs/src/examples/QasLayout/Basic.vue, package-lock.json, ui/src/components/app-menu/QasAppMenu.vue
=> Fix separator in QasAppMenu

.github/pull_request_template.md, build/build.js, build/release/create-github-release.js, build/release/git-handler.js
Mudanças para substituir branch `main-homolog` por `develop`.
=> Update develop as beta branch

CHANGELOG.md, docs/src/examples/QasFormView/Basic.vue, docs/src/examples/QasFormView/BeforeFetch.vue, docs/src/examples/QasFormView/BeforeSubmit.vue, docs/src/examples/QasFormView/Create.vue, docs/src/examples/QasFormView/Edit.vue, package.json, ui/src/components/form-view/QasFormView.vue, ui/src/components/label/QasLabel.vue
- `QasFormView`: corrigido a validação das props `useCancelButton` e `useSubmitButton`.
- `QasLabel`: modificado a classe de fonte utilizada no componente, de `text-subtitle2` para `text-subtitle1`.
=> fix(QasFormView): buttons validation

CHANGELOG.md, ui/src/components/grid-generator/QasGridGenerator.vue
- `QasGridGenerator`: refatorado código do componente para resolver problema de variável não sendo definida caso chamasse o slot `content` do componente.
=> Fix grid generator results by fields

CHANGELOG.md, app-extension/package-lock.json, app-extension/package.json, app-extension/src/boot/map.js, app-extension/src/helpers/third-party-components-handler.js, app-extension/src/index.js, ui/src/vue-plugin/components/map-component.js
- `asteroid.config.js`: correções referentes as configurações do asteroid config.
=> Fixed asteroid config

CHANGELOG.md, ui/src/mixins/search-filter.js
`search-filter.js`: corrigido problema ao limpar diversos campos relacionados a um mesmo campo de filtro.
=> search-filter: delay update:modelValue emitter

CHANGELOG.md, ui/src/components/grid-generator/QasGridGenerator.vue
`QasGridGenerator`: corrigido ordem de exibição dos `fields`.
=> fix QasGridGenerator fields order

CHANGELOG.md, ui/src/css/components/button.scss
- `ui/src/css/components/button.scss`: modificado cor disabled de `grey-8` para `grey-6` nas variantes `secondary` e `tertiary` para seguir design system.
=> Change disabled button color

CHANGELOG.md, ui/src/components/form-view/QasFormView.vue, ui/src/components/form-view/QasFormView.yml
- `QasFormView`: adicionado nova prop `formProps` para repassar todas as props/eventos para o `QForm`.
=> Added formProps to QasFormView

CHANGELOG.md, docs/src/examples/QasPageHeader/BreadcrumbsEllipsis.vue, docs/src/pages/components/page-header.md, ui/src/components/page-header/QasPageHeader.vue
- `QasPageHeader`: adicionado `ellipsis` em cada item do `breadcrumbs` setando os mesmo com no máximo `180px`, a partir desse tamanho sera adicionado o ellipsis.
=> Changes in QasPageHeader

CHANGELOG.md, ui/src/helpers/promise-handler.js
- `helpers/promiseHandler`: corrigido `Loading.hide()` mesmo quando a flag `useLoading` era false, isto fazia que cancelasse qualquer loading da aplicação.
=> Fixed promiseHandler

CHANGELOG.md, docs/src/components/DocApi.vue, ui/src/components/app-user/QasAppUser.yml, ui/src/components/dialog/QasDialog.vue, ui/src/components/dialog/QasDialog.yml, ui/src/components/field/QasField.yml, ui/src/components/filters/QasFilters.yml, ui/src/components/form-view/QasFormView.vue, ui/src/components/form-view/QasFormView.yml, ui/src/components/gallery/QasGallery.yml, ui/src/components/grid-generator/QasGridGenerator.yml, ui/src/components/search-input/QasSearchInput.yml
- `QasFormView`: modificação do `data-cy` dos botões de "Salvar" e "Voltar" do formulário. Veja mais detalhes na seção "Modificado" abaixo.
- `QasDialog`: adicionado `data-cy` em algumas seções do componente. Como, por exemplo: título, descrição, botões, etc.
- `QasFormView`: modificado `data-cy` do botão de "Salvar" para `data-cy="form-view-submit-btn-[entity]"`.
- `QasFormView`: modificado `data-cy` do botão de "Voltar" para `data-cy="form-view-cancel-btn-[entity]"`.
=> QasDialog: add data-cy to the component

CHANGELOG.md, ui/src/components/app-bar/QasAppBar.vue
- `QasAppBar`: alterado componente para Composition API.
=> Refactor QasAppBar component to use Composition API

CHANGELOG.md, ui/src/components/box/QasBox.vue
- `QasBox`: alterado componente para Composition API.
=> Refactor QasBox component to use Composition API

CHANGELOG.md, ui/src/components/avatar/QasAvatar.vue, ui/src/components/avatar/enums/AvatarColors.js
- `QasAvatar`: alterado componente para Composition API.
=> Refactor QasAvatar component to use Composition API

.vscode/settings.json, CHANGELOG.md, docs/src/boot/asteroid.js, ui/src/components/app-user/QasAppUser.vue
- `QasAppUser`: alterado componente para Composition API.
=> Refactor component QasAppUser to use Composition API

CHANGELOG.md, docs/src/pages/plugins/delete.md, ui/src/components/actions-menu/QasActionsMenu.vue, ui/src/vue-plugin.js
=> fix: composition api fix to use Delete plugin

CHANGELOG.md, ui/src/components/app-bar/QasAppBar.vue
`QasAppBar.vue`: alterado `max-width` da logo para `115px`.
=> QasAppBar: changed brand image max-width

CHANGELOG.md, ui/src/components/app-menu/QasAppMenu.vue
=> fix: QasAppMenu open and close animation

CHANGELOG.md, ui/src/components/btn-dropdown/QasBtnDropdown.vue
- `QasBtnDropdown`: alterado componente para Composition API.
=> Refactor QasBtnDropdown to Composition API

CHANGELOG.md, ui/src/components/copy/QasCopy.vue
- `QasCopy`: alterado componente para Composition API.
=> Refactor QasCopy to Composition API

CHANGELOG.md, ui/src/components/header-actions/QasHeaderActions.vue, ui/src/components/header-actions/QasHeaderActions.yml
- `QasHeaderActions`: alterado componente para Composition API.
=> Refactor QasHeaderActions to Composition API

CHANGELOG.md, ui/src/components/list-items/QasListItems.vue
- `QasListItems`: alterado componente para Composition API.
=> Refactor QasListItems to Composition API

CHANGELOG.md, ui/src/components/map/QasMap.vue
- `QasMap`: alterado componente para Composition API.
=> Refactor QasMap to Composition API

CHANGELOG.md, ui/src/components/page-header/QasPageHeader.vue
- `QasPageHeader`: alterado componente para Composition API.
=> Refactor QasPageHeader to Composition API

CHANGELOG.md, ui/src/components/pagination/QasPagination.vue
- `QasPagination`: alterado componente para Composition API.
=> Refactor QasPagination to Composition API

CHANGELOG.md, docs/src/assets/menu.js, docs/src/examples/QasWhatsappLink/Basic.vue, docs/src/pages/components/whatsapp-link.md, ui/src/components/whatsapp-link/QasWhatsappLink.vue, ui/src/components/whatsapp-link/QasWhatsappLink.yml, ui/src/vue-plugin.js
- `QasWhatsappLink`: adicionado novo componente de link para o Whatsapp.
=> QasWhatsappLink component

CHANGELOG.md, app-extension/package-lock.json, ui/src/components/layout/QasLayout.vue
- `QasLayout`: propriedade "initialUnreadNotificationsCount" só era escutada por uma vez, o que gerava problemas quando os dados eram alterados.
=> Fixed QasLayout issue with notifications counter

CHANGELOG.md, docs/src/examples/QasDate/ExDateEvents.vue, ui/src/components/date/QasDate.vue
- `QasDate`: Corrigido exibição de eventos com mais de 3 dígitos no calendário.
=> fix: QasDate calendar event exhibition

CHANGELOG.md, ui/src/components/list-items/QasListItems.vue
- `QasListItens`: resetado `min-height` que existia no q-item.
=> Changes in QasListItems

CHANGELOG.md, ui/src/components/app-user/QasAppUser.vue
- `QasAppUser`: Alterado do menu "Editar" para "Perfil", uma vez que agora a pagina do /me não é somente para editar.
=> Changes in QasAppUser to change profile label

CHANGELOG.md, ui/src/components/card/QasCard.vue
=> feat: insert max width in qas-card

CHANGELOG.md, ui/src/components/app-menu/QasAppMenu.vue, ui/src/components/app-menu/QasAppMenu.yml, ui/src/components/app-menu/private/PvAppMenuHelpChat.vue
- `QasAppMenu`: adicionado propriedade `helpChatLink`, para a ação de "Solicitar ajuda".
=> QasAppMenu: help chat

CHANGELOG.md, docs/src/examples/QasAppMenu/Basic.vue, ui/src/components/app-menu/private/PvAppMenuHelpChat.vue
- `QasAppMenu`: adicionado validações para garantir que aconteça nenhum erro que trave a aplicação.
=> help chat fix

CHANGELOG.md, docs/src/examples/QasActionsMenu/ExOptions.vue, docs/src/examples/QasHeaderActions/HeaderActionsWithButton.vue, ui/src/components/actions-menu/QasActionsMenu.vue, ui/src/components/header-actions/QasHeaderActions.vue, ui/src/components/header-actions/QasHeaderActions.yml
- `QasActionsMenu`: possibilidade de passar a prop `to` para os botões.
- `QasHeaderActions`: adicionado prop `margin`.
=> feat: added actions props

CHANGELOG.md, docs/src/examples/QasExpansionItem/Basic.vue, docs/src/examples/QasExpansionItem/Error.vue, docs/src/examples/QasExpansionItem/HeaderBottomSlot.vue, docs/src/examples/QasExpansionItem/Nested.vue, docs/src/examples/QasExpansionItem/Slot.vue, docs/src/pages/components/expansion-item.md, ui/src/components/expansion-item/QasExpansionItem.vue, ui/src/components/expansion-item/QasExpansionItem.yml
- `QasExpansionItem`: adicionado novo slot `header-bottom`.
- `QasExpansionItem`: modificado layout do componente quando ele é usado como nested (QasExpansionItem dentro de QasExpansionItem).
=> QasExpansionItem nested changes

CHANGELOG.md, docs/src/assets/menu.js, docs/src/examples/QasToggleVisibility/Basic.vue, docs/src/examples/QasToggleVisibility/MultipleGroup.vue, docs/src/examples/QasToggleVisibility/Slot.vue, docs/src/pages/components/toggle-visibility.md, ui/src/components/toggle-visibility/QasToggleVisibility.vue, ui/src/components/toggle-visibility/QasToggleVisibility.yml, ui/src/composables/private/index.js, ui/src/composables/private/use-toggle-visibility.js, ui/src/vue-plugin.js
- `QasToggleVisibility`: Adicionado novo componente.
=> Added QasToggleVisibility

CHANGELOG.md, docs/src/pages/components/single-view.md, ui/src/components/btn-dropdown/QasBtnDropdown.vue, ui/src/components/header-actions/QasHeaderActions.vue, ui/src/components/single-view/QasSingleView.vue
=> fix: header actions adjustments

CHANGELOG.md, app-extension/src/boot/notifications.js
- `boot/notifications`: removido notificações em localhost, uma vez que ficava gerando vários errors de conexão no console/network, o que atrapalhava o desenvolvimento local.
=> Remove localhost notifications

CHANGELOG.md, ui/src/components/form-view/QasFormView.vue, ui/src/components/form-view/QasFormView.yml, ui/src/components/grid-generator/QasGridGenerator.vue, ui/src/components/label/QasLabel.vue, ui/src/components/list-view/QasListView.vue, ui/src/components/list-view/QasListView.yml, ui/src/components/single-view/QasSingleView.vue, ui/src/components/single-view/QasSingleView.yml, ui/src/composables/private/use-generator.js, ui/src/composables/private/use-view.js, ui/src/mixins/view.js
=> feat: asteroid adjustments

CHANGELOG.md, ui/src/components/single-view/QasSingleView.vue, ui/src/composables/private/use-view.js, ui/src/mixins/view.js
=> fix single view

CHANGELOG.md, docs/src/examples/QasActions/WithTertiary.vue, docs/src/pages/components/actions.md, ui/src/components/actions/QasActions.vue
- `QasActions`: adicionado nova opção de ação terciária.
=> QasActions changes

CHANGELOG.md, docs/src/examples/QasActions/Basic.vue, docs/src/examples/QasActions/WithTertiary.vue, ui/src/components/actions/QasActions.vue
=> QasActions: fix small screen button size

CHANGELOG.md, app-extension/package-lock.json, app-extension/package.json, docs/package-lock.json, docs/package.json, docs/src/examples/QasActions/Basic.vue, docs/src/examples/QasActions/WithTertiary.vue, package-lock.json, package.json, ui/package-lock.json, ui/package.json, ui/src/components/actions/QasActions.vue
- Corrigido tamanho dos botões do `QasActions` em casos de telas pequenas, no qual se deve ficar tamanho total da largura.
=> Releasing v3.16.1

CHANGELOG.md, docs/src/examples/QasFormGenerator/WithButton.vue, docs/src/examples/QasInput/Counter.vue, docs/src/examples/QasSearchInput/InsideBox.vue, docs/src/examples/QasSelectListDialog/InsideBox.vue, docs/src/examples/QasTableGenerator/HeaderSlot.vue, docs/src/examples/QasTableGenerator/WithHeader.vue, docs/src/pages/components/form-generator.md, docs/src/pages/components/input.md, docs/src/pages/components/search-input.md, docs/src/pages/components/select-list-dialog.md, docs/src/pages/components/table-generator.md, docs/src/pages/styles/border.md, ui/src/components/dialog/QasDialog.vue, ui/src/components/form-generator/QasFormGenerator.vue, ui/src/components/search-input/QasSearchInput.vue, ui/src/components/select-list-dialog/QasSelectListDialog.vue, ui/src/components/table-generator/QasTableGenerator.vue, ui/src/components/table-generator/QasTableGenerator.yml, ui/src/css/utils/border.scss
=> feat(QasSelectListDIalog): remove box inside box

CHANGELOG.md, docs/src/examples/QasInput/Textarea.vue, ui/src/components/table-generator/QasTableGenerator.vue
- `QasTableGenerator`: modificado layout de espaçamentos e borda da tabela.
=> QasTableGenerator layout changes

CHANGELOG.md, docs/src/examples/QasSelect/AutoSelect.vue, docs/src/examples/QasSelect/Required.vue, docs/src/pages/components/select.md, ui/src/components/select/QasSelect.vue, ui/src/components/select/QasSelect.yml
=> feat(QasSelect): select auto fill

CHANGELOG.md, docs/package-lock.json, docs/package.json, docs/src/examples/QasGridGenerator/BoxAndHeader.vue, docs/src/pages/components/grid-generator.md, ui/src/components/grid-generator/QasGridGenerator.vue, ui/src/components/grid-generator/QasGridGenerator.yml
- `QasGridGenerator`: adicionado novas propriedades `use-box`, `box-props` e `header-props`.
=> QasGridGenerator changes

CHANGELOG.md, docs/src/examples/QasSelect/CustomOption.vue, docs/src/pages/components/select.md, ui/src/components/select/QasSelect.vue, ui/src/components/select/QasSelect.yml, ui/src/css/components/item.scss
=> feat(QasSelect): custom slot

CHANGELOG.md, docs/src/examples/QasFormGenerator/CustomSlot.vue, docs/src/examples/QasFormGenerator/Fieldset.vue, ui/src/components/form-generator/QasFormGenerator.vue, ui/src/components/form-generator/QasFormGenerator.yml
- `QasFormGenerator`: criado slot `after-[nome-do-fieldset]`.
closes #1176 
=> `QasFormGenerator`: added `legend-bottom-[nome-da-chave]` slot.

CHANGELOG.md, ui/src/components/chart-view/QasChartView.vue
… displayed
- `QasChartView`: corrigido tamanho mínimo do componente quando não existem items há serem exibidos.
=> QasChartview: fix spacing

CHANGELOG.md, docs/src/assets/menu.js
- `QasCheckbox`: corrigido documentação do componente.
=> feat: fix checkbox docs

CHANGELOG.md, ui/src/components/chart-view/QasChartView.vue
- `QasChartView`: corrigido altura mínima ao fazer fetch.
=> `QasChartView`: fix min height on loading.

CHANGELOG.md, ui/src/components/board-generator/QasBoardGenerator.vue
=> fix(QasBoardGenerator): fix drop card confirm dialog

CHANGELOG.md, docs/src/examples/QasAvatar/Basic.vue, docs/src/pages/components/avatar.md, ui/src/components/avatar/QasAvatar.vue
- `QasAvatar`: adicionado possibilidade de passar cores fora das defaults.
=> QasAvatar: colors changes.

CHANGELOG.md, ui/src/components/app-menu/QasAppMenu.vue
- `QasAppMenu`: removido prefixo `+` no phone enviado para o gleap que estava incorreto.
=> HOTFIX: Fix QasAppMenu phone formatting for Gleap integration

CHANGELOG.md, docs/src/examples/QasWelcome/SlotAfterGreeting.vue, docs/src/pages/components/welcome.md, ui/src/components/select/QasSelect.vue, ui/src/components/select/QasSelect.yml, ui/src/components/welcome/QasWelcome.vue, ui/src/components/welcome/QasWelcome.yml
- `QasWelcome`: Adicionado slot `after-greeting` para acessar conteúdo após saudações.
- `QasSelect`: 
- Corrigido lógica para setar o model com a única option disponível.
- Corrigido alinhamento das badges.
=> QasSelect/QasWelcome Adjustments

CHANGELOG.md, docs/src/examples/QasTableGenerator/WithFieldsProps.vue, ui/src/components/table-generator/_components/PvTableGeneratorTd.vue
=> fix(QasTableGenerator): prevent and stop propagation

CHANGELOG.md, docs/src/examples/QasFormGenerator/WithSubsets.vue, docs/src/examples/QasFormGenerator/WithSubsetsSlots.vue, docs/src/pages/components/form-generator.md, ui/src/components/form-generator/QasFormGenerator.vue, ui/src/components/form-generator/QasFormGenerator.yml
- `QasFormGenerator`: adicionado possibilidade de ter subseções (`subset`) dentro de uma seção (`fieldset`). Para mais detalhes, consultar a documentação.
=> QasFormGenerator: Subset

CHANGELOG.md, ui/src/components/btn/QasBtn.vue
- `QasBtn`: ajustado espaçamento do botão, estava causando quebra em alguns lugares como no menu da aplicação.
=> QasBtn: corrigido espaçamento

CHANGELOG.md, docs/src/examples/QasCard/Basic.vue, ui/src/components/card/QasCard.vue
- `QasCard`: Modificado espaçamentos do card.
- `QasCard`: Corrigido borda à esquerda dos cards que não possuem status.
=> feat: Espaçamentos do card/Borda dos cards que não possuem status.

CHANGELOG.md, ui/src/components/select-list-dialog/QasSelectListDialog.vue
`QasSelectListDialog`: Corrigido espaçamento abaixo do header, no qual estava adicionando sem necessidade.
=> `QasSelectListDialog`: Corrigido espaçamento do header

CHANGELOG.md, ui/src/components/table-generator/QasTableGenerator.vue
- `QasTableGenerator`: Alterado cor do título da coluna (th) para o `grey-10`.
Closes #1287 
=> `QasTableGenerator`: Alterado cor do título da coluna (th) para o `grey-10`.
