bildvitta/asteroid

CHANGELOG.md
ui/src/helpers/historyHandler.js

- Added method in `historyHandler` for destroy routes by names list
Closes #197

fix: insert method destroy in historyHandler

---

ui/src/components/nested-fields/QasNestedFields.vue

Esse foi um bug encontrado durante o desenvolvimento do nested fields dentro do hub-client.
Basicamente ele não estava transformando de snake case (nome-da-parada) para camel case (nomeDaParada) dentro dos "childrens" de um fields com nested, creio eu que o humps e a aplicação dele se limita aos campos de dentro de fields, e não vai até o fields.children (que é como apresentamos os campos de um nested fields) para alterar o modelo da propriedade name para o padrão que utilizamos

NestedFields - Treating snake or kebab-case to camel-case inside childrens

---

CHANGELOG.md
ui/src/components/app-bar/QasAppBar.vue
ui/src/components/avatar/QasAvatar.vue

We are receiving the url from backend inside our user requests, I don't feel the nececity of running into the humanaze 'asset' function.
Perhaps shoud run this request inside the client aplication, not here
---
Estamos recebendo a url do backend dentro de nossas solicitações de usuário, não sinto a necessidade de executar a função de 'ativo' humanaze.
Talvez deva executar esta solicitação dentro da aplicação do cliente, não aqui

Removing asset from qas-avatar inside AppBar

---

CHANGELOG.md
ui/src/components/copy/QasCopy.stories.js
ui/src/components/copy/QasCopy.vue

Requerido por Lucas Tomazini para o Design System: o tamanho default do ícone do `QasCopy` deve ser `sm`, e não `xs` como anteriormente
Houve mudanças no componente, aceitando agora uma prop para o size (caso queira mandar outro tamanho) e como default o `sm` e mudanças no arquivo do story desse componente para explicar como usar a prop

QasCopy - changes on icon default size

---

CHANGELOG.md
ui/src/components/map/QasMap.vue
ui/src/mixins/map-markers.js

O QasMaps estava carregando internamente um QasBox, deixei isso para a página controlar.
O mixin $_createMarkers não estava funcionando corretamente, substituí por uma implementação já com os tratamentos necessários sobre o que é location e o que é ponto de referência. Incluindo tratamento de draggable e de icon.

removing qas-box from maps / refactoring

---

CHANGELOG.md
ui/src/components/form-view/QasFormView.vue
ui/src/mixins/unsaved-changes.js

Ao deletar um "objeto" dentro de uma tela de edit, um dos comportamentos mais comuns no deleteSuccess pode da mudança de rota, com o `router.push` por exemplo, se em algum momento, o values ficar diferente do que estava inicialmente na tela, ele faz a função de deletar e logo após isso (na mudança de rota do deleteSuccess) ele abre o modal do edit, travando a mudança da rota.
Nesse momento, ao clicar em "Continuar editando" o sistema quebra, afinal de contas, ele deletou o item que ele esta tentando continuar editando
Em conversa com o @DouglasCalora, foi criado dentro do mixin do `unsaved-changes` um metodo para avisar quando será acionado um method de delete para passar por cima dessas mudanças no edit
```
deleteSuccess () {
this.$_deleteSuccess()
this.$router.push({ name: …
```

unsaved-changes for delete actions

---

CHANGELOG.md
ui/dev/src/pages/TestListItems.vue
ui/dev/src/pages/TestResizer.vue
ui/src/components/list-items/QasListItems.stories.js
ui/src/components/list-items/QasListItems.vue
ui/src/components/resizer/QasResizer.vue

Foi encontrado uma limitação do componente quando precisávamos com que o `redirect-key` fosse algum outro valor q fosse diferente de `id`, causava q a rota que iria ser redirecionado, esperava  o valor dessa chave em seu `params`, fazendo com que o vue-router e o single-view se perca. Criamos uma nova prop para que o valor e a chave do params não seja unificado.

Added new prop paramKey to QasListItems.

---

CHANGELOG.md
ui/src/components/filters/QasFilters.stories.js
ui/src/components/filters/QasFilters.vue

Inserção de uma nova propriedade `forceRefetch` no componente `QasFilters`. Essa propriedade força a atualização dos filtros sempre ao mudar de página. 
Removida a ação `@before-show="fetchFilters"` da tag `q-menu` no componente `QasFilters`. Aparentemente esta ação nunca foi necessária para que o componente funcionasse corretamente.

Added new prop forceRefetch to QasFilters

---

CHANGELOG.md
ui/src/components/search-box/QasSearchBox.stories.js
ui/src/components/select-list/QasSelectList.vue
ui/src/components/select/QasSelect.stories.js
ui/src/components/select/QasSelect.vue
ui/src/mixins/lazy-loading-filter.js

Ajustes encontrados no uso da versão beta do v2.23.0-beta.4:
* Limpeza do filtro ao mudar os parâmetros de url e query do lazy loading;
* Novo evento de `fetching` ao buscar por novas opções na API;
* Melhoria no texto de loading do QasSelect;
* Adicionado q-list wrapper para os q-item no componente QasSelectList.

Support/v2.23.0 beta.5 fixes

---

CHANGELOG.md
ui/src/components/search-box/QasSearchBox.vue
ui/src/components/select/QasSelect.vue
ui/src/mixins/lazy-loading-filter.js

Ajustes encontrados no uso da versão beta do v2.23.0-beta.5:
- `QasSelect`: adicionado o slot padrão `hint` para mostrar um texto de carregamento.
- `QasSelect`: adicionado suporte para receber o atributo `loading` externamente e funcionar em conjunto com o `isLoading` interno.
- `QasSelect`: corrigido um bug com o retorno do callback update do evento `onFilter` e solicitações AJAX. Agora o callback `update` é chamado apenas quando as opções são populadas usando o lazy loading. [Link para uma issue parecida](https://stackoverflow.com/questions/71312696/quasar-qselect-is-not-opening-when-performing-ajax-call)
- `lazyLoadingFilterMixin`: corrigido um erro de scroll quando o usuário rola para baixo e pede por mais opções utilizando o virtual scroll.
Este _pull request_ introduz algum …

Support/v2.23.0 beta.6 fixes

---

.vscode/settings.json
CHANGELOG.md
README.md
docs/src/assets/menu.js
docs/src/pages/components/search-box.md
docs/src/pages/components/select.md
docs/src/pages/helpers/get-normalized-options.md
ui/src/components/dialog/QasDialog.yml
ui/src/components/field/QasField.vue
ui/src/components/input/QasInput.vue
ui/src/components/search-box/QasSearchBox.vue
ui/src/components/search-box/QasSearchBox.yml
ui/src/components/select-list/QasSelectList.vue
ui/src/components/select/QasSelect.vue
ui/src/components/select/QasSelect.yml
ui/src/helpers/get-normalized-options.js
ui/src/helpers/index.js
ui/src/mixins/index.js
ui/src/mixins/lazy-loading-filter.js
ui/src/mixins/search-filter.js

- [`QasSelect`, `QasSearchBox`]: adicionada props: `useLazyLoading`, `name`, `entity` e `useLazyLoadingProps` para adicionar funcionalidades do lazy loading semelhante a versão 2 do asteroid: https://github.com/bildvitta/asteroid/pull/573/files
- [`QasSelect`, `QasSearchBox`]: adicionada eventos: `@fetch-options-error`, `@fetch-options-success` e `@update:fetching` referentes ao lazy loading.
- `QasSearchBox`: adicionado slot loading referente ao lazy loading.
- `QasField`: repassando `entity`, `name` e `useLazyLoading` ao componente `QasSelect`.
- Adicionado novo helper `getNormalizedOptions`.
- Adicionado novo mixin `lazyLoadingFilterMixin` para ser usado tanto no `QasSelect` quanto no `QasSearchBox`
- `QasSearchBox`: Adicionado propriedade `emptyResultText` com default `Não há …

Beta - 17 / lazy loading

---

.vscode/settings.json
CHANGELOG.md
docs/src/components/DocApiEntry.vue
ui/src/components/date-time-input/QasDateTimeInput.vue
ui/src/components/field/QasField.vue
ui/src/components/form-generator/QasFormGenerator.vue
ui/src/components/input/QasInput.vue
ui/src/components/password-input/QasPasswordInput.vue

Correção de um bug causado na versão beta.19. Esse bug se origina na retirada das divs que englobavam alguns componentes, como: `QasField`, `QasInput` e mais. 
Esse bug causava um problema em que todos os atributos eram herdados automaticamente aos componentes, sendo que, já há um `v-bind` nesses componentes com os atributos tratados.

fix: :bug: inheritAttrs with value false added to some components

---

CHANGELOG.md
docs/src/examples/QasTabsGenerator/TabsArray.vue
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/tabs-generator/QasTabsGenerator.vue
ui/src/components/tabs-generator/QasTabsGenerator.yml

- `QasActionsMenu`: Alterado propriedade `use-label-on-small-screen` para `:use-label-on-small-screen="false"` para seguir o padrão.
- `QasTabsGenerator`: Alterado type do `modelValue` para `[String, Number]` para aceitar numbers também.
- `QasTableGenerator`: Alterado `counters[key]` para `counters[tab.value]` para funcionar o counters quando utilizar tabs como `array`.

fix: Fixed QasTabsGenerator and QasActionsMenu

---

.vscode/settings.json
CHANGELOG.md
ui/src/components/nested-fields/QasNestedFields.vue

- `QasNestedFields`: Adicionado prop `deep: true` no watch no `modelValue` para resolver bug quando usa um custom slot, ou altera o v-model e perde a reatividade.

fix(QasNestedFields): :bug: fix reactive in modelValue watch

---

CHANGELOG.md
ui/src/components/app-bar/QasAppBar.vue

- `QasAppBar`: adicionado classe `no-wrap` para não quebrar o menu de usuário.

fix: :bug:(QasAppBar) added no-wrap class in user-menu

---

CHANGELOG.md
docs/src/examples/QasPasswordInput/Basic.vue
ui/src/components/app-bar/QasAppBar.vue
ui/src/components/field/QasField.vue
ui/src/components/password-input/QasPasswordInput.vue
ui/src/components/search-box/QasSearchBox.vue

- `QasField`: repassando `useStrengthChecker` no QasField.
- `QasSearchBox`: modificado tempo de `debounce` no lazy loading de `500` para `800`.
- `QasSearchBox`: removido `disable` do campo de busca enquanto ocorria uma request.
- `QasAppBar`: corrigido badge que mostra se o ambiente é de `Develop`.
- `QasPasswordInput`: corrigido problema de slots que não mostrada `QasPasswordStrengthChecker` quando renderizado pelo `QasField` e também não respeitava a prop `hideBottomSpace` quando usado diretamente.

v3.4.0-beta.1

---

CHANGELOG.md
ui/src/components/form-generator/QasFormGenerator.vue

- `QasFormGenerator`: corrigido problema que não deixava campo disabled quando a prop vinha pelo `QasField`.

fix(QasFormGenerator): fixed disable

---

.vscode/settings.json
CHANGELOG.md
app-extension/package-lock.json
app-extension/package.json
docs/package-lock.json
docs/package.json
docs/src/assets/menu.js
docs/src/boot/asteroid.js
docs/src/examples/QasFilters/Basic.vue
docs/src/examples/QasOptionGroup/Basic.vue
docs/src/examples/QasSelect/Searchable.vue
docs/src/pages/components/option-group.md
package-lock.json
package.json
ui/package-lock.json
ui/package.json
ui/src/components/field/QasField.vue
ui/src/components/filters/QasFilters.vue
ui/src/components/filters/QasFilters.yml
ui/src/components/option-group/QasOptionGroup.vue
ui/src/components/option-group/QasOptionGroup.yml
ui/src/components/select/QasSelect.vue
ui/src/components/select/QasSelect.yml
ui/src/css/variables/button.scss
ui/src/css/variables/typography.scss
ui/src/vue-plugin.js

- `QasField`: Alterado type `radio` par utilizar o novo componente `QasOptionGroup` e removido prop de erro pois não existe no componente `QOptionGroup`, testar bem para validar.
- Componentes de radio agora existe padronização, a partir do mobile componente segue comportamento de linha, em telas mobile segue comportamento de bloco, não sendo possível alterar este comportamento, verificar locais que utilizam para não quebrar o estilo.
- `QasFilters`: adicionado nova propriedade `fieldsProps` para repassar propriedades para os campos do filtro.
- `QaSelect`: adicionado busca automaticamente quando existem pelo menos 10 opções.
- `QasOptionGroup`: adicionado novo componente wrapper do `QOptionGroup` do quasar, para deixar padronizado propriedade `inline` e deixar mais componentizado.
- …

v3.5.0-beta.0

---

.vscode/settings.json
CHANGELOG.md
docs/src/examples/QasActionsMenu/Basic.vue
docs/src/examples/QasActionsMenu/CustomSlot.vue
docs/src/pages/components/actions-menu.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/actions-menu/QasActionsMenu.yml
ui/src/components/actions-menu/private/PvActionsMenuList.vue

Modificação do estilo padrão do componente `QasActionsMenu` e do comportamento quando há uma ou mais ações.
**Mais de uma ação:**
**Apenas uma ação:**

QasActionsMenu new styles and behaviors

---

CHANGELOG.md
docs/src/examples/QasNestedFields/Basic.vue
docs/src/examples/QasNestedFields/StartsEmptyFalse.vue
docs/src/pages/components/nested-fields.md
ui/src/components/nested-fields/QasNestedFields.vue
ui/src/components/nested-fields/QasNestedFields.yml

O novo comportamento deve trazer um texto para que o usuário clique e para só então exibir os campos do nested.

Add option to QasNestedFields starts empty.

---

CHANGELOG.md
ui/src/components/delete/QasDelete.vue
ui/src/components/form-view/QasFormView.vue
ui/src/css/plugins/notify.scss
ui/src/mixins/view.js

- Alterado mesagem padrão do `QasFormView`, `view.js`, `QasDelete`.
- Adicionado tamanho máximo ao notify
clickup: https://app.clickup.com/t/864dj3zdr

Changes in notify and default message

---

CHANGELOG.md
docs/src/examples/QasNestedFields/InlineActions.vue
ui/src/components/nested-fields/QasNestedFields.vue

Resolvido problema do botão de excluir.
clickup: https://app.clickup.com/t/864dj6bk8

Fix destroy always on QasNestedFields

---

CHANGELOG.md
ui/src/components/delete/QasDelete.vue
ui/src/components/page-header/QasPageHeader.vue

Removido botão de voltar do QasPageHeader:
clickup: https://app.clickup.com/t/35k1dp6

Removed back button from QasPageHeader

---

CHANGELOG.md
ui/src/components/app-menu/QasAppMenu.vue
ui/src/components/select/QasSelect.vue

Removido opção de busca do select de modulos do menu.

Fix app menu search select

---

CHANGELOG.md
ui/src/components/select/QasSelect.yml

Adicionado "useSearch" na documentação do QasSelect.

Add useSearch docs

---

CHANGELOG.md
docs/src/examples/QasFilters/Basic.vue
docs/src/pages/components/filters.md
ui/src/components/filters/QasFilters.vue
ui/src/components/filters/QasFilters.yml
ui/src/components/page-header/QasPageHeader.vue
ui/src/index.scss

-`ui/src/index.scss`: adicionado nova variável css para transição: `--qas-generic-transition: 300ms`;
- `QasFilters`: mudanças de design.
- `QasFilters`: alterado debounce de `500ms` para `800ms`.
- `QasPageHeader`: alterado espaçamento de `q-mb-lg` para `q-mb-xl` para manter o que era anteriormente.
clickup: https://app.clickup.com/t/3ehb3m0

QasFilters Changes

---

CHANGELOG.md
ui/src/components/field/QasField.vue

- `QasField`: agora o label de required também é modificado caso passe através dos `$attrs`.
clickup: https://app.clickup.com/t/864djyrxd

Added required label for $attrs

---

CHANGELOG.md
ui/src/components/form-view/QasFormView.vue

- `QasFormView`: modificado comportamento da propriedade `disable`, agora só desabilita o botão de salvar (submit), deixando o botão voltar habilitado.
clickup: https://app.clickup.com/t/864djudzd

Change behaviour of prop disable on QasFormView

---

CHANGELOG.md
app-extension/src/templates/css/quasar.variables.scss
docs/src/components/DocToken.vue
docs/src/css/quasar.variables.scss
docs/src/pages/start/usage.md
docs/src/pages/styles/border.md
docs/src/pages/styles/set-brand.md
ui/dev/src/css/quasar.variables.scss
ui/src/components/alert/QasAlert.vue
ui/src/components/avatar/QasAvatar.vue
ui/src/components/box/QasBox.vue
ui/src/components/card/QasCard.vue
ui/src/components/transfer/QasTransfer.vue
ui/src/css/utils/border.scss
ui/src/index.scss

- `border.scss`: adicionado nova cor de borda `border-grey`.
- `index.scss`: adicionado nova var css `--qas-border-grey`.
- [`QasAlert`, `QasAvatar`, `QasBox`, `QasCard`, `QasTransfer`]: modificado cores referente a `primary-contrast` e `secondary-contrast`.
- `quasar.variables.scss`: modificado cores.
`QasAvatar`: removido propriedades `color` e `text-color` agora sempre vai ser background primary com cor de texto branca.
clickup: https://app.clickup.com/t/864dkdhkq

Color changes

---

CHANGELOG.md
docs/src/assets/menu.js
docs/src/examples/QasHeaderActions/HeaderActionsWithActionsMenu.vue
docs/src/examples/QasHeaderActions/HeaderActionsWithButton.vue
docs/src/examples/QasHeaderActions/HeaderActionsWithSlots.vue
docs/src/examples/QasPageHeader/Basic.vue
docs/src/examples/QasPageHeader/HeaderActionsWithActionsMenu.vue
docs/src/examples/QasPageHeader/HeaderActionsWithButton.vue
docs/src/examples/QasPageHeader/WithBottomSlot.vue
docs/src/examples/QasPageHeader/WithMoreLevels.vue
docs/src/pages/components/header-actions.md
docs/src/pages/components/page-header.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/header-actions/QasHeaderActions.vue
ui/src/components/header-actions/QasHeaderActions.yml
ui/src/components/page-header/QasPageHeader.vue
ui/src/components/page-header/QasPageHeader.yml
ui/src/css/variables/typography.scss
ui/src/vue-plugin.js

- `QasPageHeader`: adicionada nova propriedade `useHomeIcon` que habilita o ícone de início como primeiro nível do breadcrumbs, com default `true` para respeitar novo padrão de design, caso já tenha um nível de "início" declaro no breadcrumbs, remova.
- `QasHeaderActions`: adicionado novo componente para trabalhar com descrição e ações.
- `QasPageHeader`: mudanças de layout e comportamento, agora caso o breadcrumbs tenha mais de 4 níveis é adicionado uma label "...".
- `typography.scss`: alterado `font-weight` do `$caption` para `400`.
- `QasPageHeader`: adicionada nova propriedade `useHomeIcon` que habilita o ícone de início como primeiro nível do breadcrumbs, com default `true` para respeitar novo padrão de design.
- `QasActionsMenu`: alterado valor default da propriedade …

Changes in QasPageHeader / QasActionsMenu / typography.scss / QasHeaderActions

---

CHANGELOG.md
docs/src/assets/menu.js
docs/src/pages/styles/set-typography.md
ui/src/components/pagination/QasPagination.vue
ui/src/components/table-generator/QasTableGenerator.vue
ui/src/css/mixins/index.scss
ui/src/css/mixins/set-typography.scss

- `set-typography.scss`: adicionado novo mixin para setar estilos de tipografia quando não é possível através das classes do quasar.
- `QasTableGenerator`: modificado cores e fontes.
- `QasPagination`: modificado cor das paginas para `grey-8` e cor dos ícones de setas para `grey-9`.
clickup: https://app.clickup.com/t/864dm7gah

Changes in QasTableGenerator / QasPagination / set-typograpy.scss

---

CHANGELOG.md
ui/src/components/filters/QasFilters.vue
ui/src/components/search-box/QasSearchBox.vue
ui/src/components/select/QasSelect.vue

- [`QasFilters`, `QasSearchBox`]: alterado debounce de `800ms` para `1200ms`.
- `QasSelect`: alterado debounce de `500ms` (default) para `1200ms` e quando não tem `useLazyLoading` removido o debounce.
clickup: https://app.clickup.com/t/864dm7rum

Changed debounce

---

CHANGELOG.md
ui/src/components/numeric-input/QasNumericInput.vue

- `QasNumericInput`: adicionado manualmente prefixo `R$ ` com espaçamento a mais propositalmente.
clickup: https://app.clickup.com/t/864dm9rje

Changed prefix in QasNumericInput

---

CHANGELOG.md
docs/src/examples/QasDialog/Basic.vue
docs/src/examples/QasDialog/ExWithActions.vue
docs/src/examples/QasDialog/ExWithSingleAction.vue
docs/src/pages/components/dialog.md
ui/src/components/actions/QasActions.vue
ui/src/components/actions/QasActions.yml
ui/src/components/delete/QasDelete.vue
ui/src/components/dialog/QasDialog.vue
ui/src/components/dialog/QasDialog.yml
ui/src/components/form-view/QasFormView.vue
ui/src/components/signature-uploader/QasSignatureUploader.vue
ui/src/components/text-truncate/QasTextTruncate.vue
ui/src/components/tree-generator/QasTreeGenerator.vue
ui/src/css/utils/index.scss
ui/src/css/utils/shadow.scss
ui/src/css/variables/index.scss
ui/src/css/variables/shadow.scss
ui/src/css/variables/spacing.scss
ui/src/mixins/delete.js

- `QasActions`: adicionado propriedade `use-full-width` para deixar as colunas 100%, com col-12.
- `QasActions`: adicionado propriedade `use-equal-width` para deixar as colunas 50% no desktop e 100% no mobile, col-12 col-sm-6.
`ui/src/css/variables/shadow.scss`: adicionado shadow.scss para modificar através de variável.
- `QasActions`: modificado default da propriedade `gutter` para `lg` porém no mobile ela continua `md`.
- `QasDialog`: modificado estilos do dialog.
- [`QasDelete`, `delete.js`, `QasFormView`]: removido titulo do dialog.
- `QasTreeGenerator`: removido titulo do dialog de excluir ramo.
- `spacing.scss`: modificado variáveis de gutter para aplicar mudanças do spacing.
- `QasSignatureUploader`: modificado customização do template `actions` do `qas-dialog` para utilizar o …

Changes in QasDialog

---

CHANGELOG.md
docs/src/examples/QasActionsMenu/ExUseLabel.vue
docs/src/pages/components/actions-menu.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/actions-menu/QasActionsMenu.yml
ui/src/css/components/item.scss

- `QasActionsMenu`: adicionado propriedade `useLabel` com default `true` para esconder o label em todas as telas necessárias.
- `QasActionsMenu`: adicionado propriedade `color` com default `grey-9` para controlar cor do botão.
- `QasActionsMenu`: alterado cor padrão em todos os casos para `grey-9`.
- `item.scss`: modificado cor do hover para `$primary-color`;
- `item.scss`: modificado cor do item quando clicável para `grey-9` e quando não clicável para `grey-8`;

Changes in QasActionsMenu

---

CHANGELOG.md
ui/src/components/app-menu/QasAppMenu.vue

- `QasAppMenu`: corrigido tamanho do drawer, estava invertido, 320px deve ser no mobile e não desktop.
- `QasAppMenu`: corrigido botão de fechar drawer no mobile, não tinha nenhuma ação ao clicar nele.
clickup: https://app.clickup.com/t/864dqvuzw

finished changes

---

CHANGELOG.md
ui/src/css/components/item.scss

- `item.scss`: corrigido cor quando o item está ativo, estava sobrescrevendo com a cor `grey-9` mesmo o item sendo ativo, agora não mais.
clickup: https://app.clickup.com/t/864drn44n

Fix active color in QItem.

---

CHANGELOG.md
docs/src/examples/QasTextTruncate/Basic.vue
ui/src/components/text-truncate/QasTextTruncate.vue

- `QasTextTruncate`: corrigido bug quando o texto tinha como valor inicial `undefined`.
clickup: https://app.clickup.com/t/3cxpy79

fix undefined text on QasTextTruncate

---

CHANGELOG.md
docs/src/assets/menu.js
docs/src/examples/QasStatus/Basic.vue
docs/src/pages/components/status.md
ui/src/components/status/QasStatus.vue
ui/src/components/status/QasStatus.yml
ui/src/components/tabs-generator/QasTabsGenerator.vue
ui/src/vue-plugin.js

- `QasStatus`: adicionado componente circular de status.
- `QasTabsGenerator`: utilizando `QasStatus` no lugar do `PvTabsGeneratorStatus`.
- `PvTabsGeneratorStatus`: removido componente privado em favor do componente publico `QasStatus`.

Added QasStatus

---

CHANGELOG.md
docs/src/examples/QasSearchBox/Basic.vue
ui/src/components/search-box/QasSearchBox.vue
ui/src/components/search-box/QasSearchBox.yml
ui/src/components/select/QasSelect.vue
ui/src/components/select/QasSelect.yml

- [`QasSelect`, `QasSearchBox`]: removido `threshold: 0.1`, deixando o default do `fuse.js` (0.6), assim a busca fica menos precisa e mais fácil de filtrar o que deseja.
clickup: https://app.clickup.com/t/383auth

Changed Fusejs threshold from QasSelect and QasSearchBox

---

CHANGELOG.md
ui/src/components/form-view/QasFormView.vue
ui/src/css/plugins/notify.scss
ui/src/plugins/notify-error/NotifyError.js
ui/src/plugins/notify-success/NotifySuccess.js

- [`NotifyError`, `NotifySuccess`]: adicionado flag para diferenciar notifies de erro e sucesso.
- `QasFormView`: alterado mensagem de erro de "Existem campos no formulário que ainda não foram preenchidos. Complete todas as informações para avançar." para "Não conseguimos salvar as informações. Por favor, revise os campos e tente novamente."

Changes in Notifies

---

CHANGELOG.md
app-extension/src/boot/loading.js
app-extension/src/index.js
ui/src/css/plugins/index.scss
ui/src/css/plugins/loading.scss

- [`app-extension/src/boot/loading.js`, `ui/src/css/plugins/loading.scss`]: adicionado novos arquivos para mudar o estilo do Loading.
- `Loading` adicionado estilos default para o Loading do `quasar`.
clickup: https://app.clickup.com/t/864dyu54n
Novo estilo:

Changed default style of Loading from quasar.

---

CHANGELOG.md
docs/src/examples/QasNumericInput/Negative.vue
docs/src/pages/components/numeric-input.md
ui/src/components/numeric-input/QasNumericInput.vue
ui/src/components/numeric-input/QasNumericInput.yml

`QasNumericInput`: modificado o valor padrão da propriedade `use-negative` para `false`.

QasNumericInput use negative default value

---

CHANGELOG.md
docs/src/examples/QasPasswordInput/Basic.vue
ui/src/components/input/QasInput.vue
ui/src/components/password-input/QasPasswordInput.vue
ui/src/components/password-input/QasPasswordInput.yml
ui/src/components/password-strength-checker/QasPasswordStrengthChecker.vue
ui/src/components/password-strength-checker/QasPasswordStrengthChecker.yml
ui/src/mixins/password.js

- `QasPasswordInput`: removido propriedade `iconColor` uma vez que não deve ser possível mudar a cor do ícone.
- `QasStrengthChecker`: removido model `modelValue` pois não estava sendo repassado para o `QasPasswordInput`.
- [`QasPasswordInput`, `QasStrengthChecker`]: model `currentLevel` que retorna o level atual.
- `QasPasswordInput`: Corrigido `QIcon` que foi substituído para um `QasBtn`.
- `QasPasswordInput`: Corrigido slot do hint que texto ficava em cima de conteúdos abaixo do input.
- `QasInput`: corrigido `errorMessage` que não deveria ser resetado ao usar a propriedade `use-remove-error-on-type`.
- `QasPasswordInput`: removido propriedade `iconColor` uma vez que não deve ser possível mudar a cor do ícone.
- `QasStrengthChecker`: removido model `modelValue` pois não estava sendo …

Changes in QasPasswordInput / QasStrengthChecker / QasInput

---

CHANGELOG.md
ui/src/components/pagination/QasPagination.vue

- `QasPagination`: corrigido problema com propriedade `max-content` que quebrava no `safari`.

QasPagination: fixed max-content prop that breaks in safari

---

CHANGELOG.md
docs/src/examples/QasTableGenerator/StickyHeader.vue
docs/src/pages/components/table-generator.md
ui/src/components/table-generator/QasTableGenerator.vue
ui/src/components/table-generator/QasTableGenerator.yml
ui/src/css/components/index.scss
ui/src/css/components/scrollbar.scss
ui/src/css/variables/index.scss
ui/src/css/variables/scrollbar.scss

Funcionalidade que permite que o cabeçalho da tabela permaneça visível na parte superior enquanto o usuário faz rolagem do conteúdo da tabela.

Feature/main homolog/qas table generator sticky header

---

CHANGELOG.md
docs/src/examples/QasListView/CommonUsage.vue
docs/src/examples/QasListView/ExAutoRefetchOnDelete.vue
docs/src/pages/components/list-view.md
ui/src/components/list-view/QasListView.vue
ui/src/components/list-view/QasListView.yml

- `QasListView`: adicionado propriedade `useAutoRefetchOnDelete` para controlar se o componente vai fazer o fetch novamente quando acontecer algum delete compatível com a listagem.
clickup: https://app.clickup.com/t/864dvnux9

Added prop useAutoRefetchOnDelete in QasListView

---

CHANGELOG.md
docs/src/examples/QasCopy/Basic.vue
ui/src/helpers/copy-to-clipboard.js

- `copyToClipboard`: modificado helper, agora no notify aparece sempre uma mensagem genérica "Item copiado com sucesso." ao invés do texto copiado anteriormente (isto impacta diretamente no componente `QasCopy`).

Change copy message on copyToClipboard / QasCopy

---

CHANGELOG.md
docs/src/examples/QasAppBar/Basic.vue
docs/src/examples/QasAppMenu/Basic.vue
docs/src/examples/QasAppUser/Basic.vue
docs/src/examples/QasLayout/Basic.vue
docs/src/pages/components/app-user.md
ui/src/components/app-bar/QasAppBar.vue
ui/src/components/app-bar/QasAppBar.yml
ui/src/components/app-menu/QasAppMenu.vue
ui/src/components/app-menu/QasAppMenu.yml
ui/src/components/app-user/QasAppUser.vue
ui/src/components/app-user/QasAppUser.yml
ui/src/components/list-view/QasListView.vue
ui/src/components/list-view/QasListView.yml

- [`QasAppMenu`, `QasAppBar`]: removido propriedade `user` em favor da nova propriedade `appUserProps`.
- `QasAppBar`: removido escopo `user` do slot `user`, uma vez que já temos essa informação fora do componente.
- `QasAppUser`: adicionado propriedade `currentCompany` para setar empresa atual vinculada.
- `QasAppUser`: adicionado propriedade `companiesOptions` para enviar opções de possíveis empresas para troca de vínculo.
- `QasAppUser`: adicionado recurso para troca de vínculo de empresa.
- [`QasAppMenu`, `QasAppBar`]: adicionado propriedade `appUserProps` para repassar todas props do `QasAppUser`.
- `QasListView`: adicionado nova propriedade `usePagination` para controlar paginação com default `true`.
- [`QasAppMenu`, `QasAppBar`]: removido propriedade `user` em favor da nova …

Changes in QasAppUser / QasAppMenu / QasAppBar / QasListView

---

CHANGELOG.md
docs/src/assets/menu.js
docs/src/examples/QasEmptyResultText/Basic.vue
docs/src/pages/components/empty-result-text.md
ui/src/components/empty-result-text/QasEmptyResultText.vue
ui/src/components/empty-result-text/QasEmptyResultText.yml
ui/src/components/list-view/QasListView.vue
ui/src/components/search-box/QasSearchBox.vue
ui/src/components/search-box/QasSearchBox.yml
ui/src/components/single-view/QasSingleView.vue
ui/src/mixins/search-filter.js
ui/src/vue-plugin.js

- `QasSearchBox`: removido prop `emptyResultText` para manter sempre a mesma mensagem quando não encontra itens.
- `QasEmptyResultText`: adicionado novo componente para resultados vazio.
- `QasSearchBox`: alterado default da prop `emptyResultText` para `Não há itens para serem exibidos.`
- `QasSearchBox`: alterado estilo de quando não não há itens para serem exibidos.
- [`QasSearchBox`, `QasListView`, `QasSingleView`]: adicionado componente `QasEmptyResultText`.
- `QasSearchBox`: corrigido primeiro fetch quando existe `options` antes de finalizar o primeiro `fetch`.
- `ui/src/mixins/search-filter.js`: corrigido duplicidade de opções quando acontece mais de requisição em paralelo pelas mudanças causadas no `lazyLoadingProps`.

Changes in QasSearchBox/QasListView/QasSingleView/search-filter.js and added new component QasEmptyResultText

---

CHANGELOG.md
ui/src/components/filters/QasFilters.vue

- `QasFilters`: tratamento para passar os `fieldsProps` utilizando as chaves dos fields em camelCase para mantermos o padrão.
- `QasFilters`: Ao selecionar o botão de limpar, irá limpar somente os campos do filtro e da query, mantendo outros filtros externos na query.
- `QasFilters`: tratamento para não filtrar na query campos que não possuem valores.

feat(QasFilters): handle query values

---

CHANGELOG.md
docs/package-lock.json
package-lock.json
ui/src/mixins/search-filter.js

- `search-filter.js`: corrigido problema de quando as opções externas são setadas após o fetch interno de opções, que fazia que as opções externas sobrescreviam as opões interna erroneamente.

Fixed `search-filter.js`

---

CHANGELOG.md
docs/src/examples/QasFilters/NoRouteUpdate.vue
ui/src/components/filters/QasFilters.vue
ui/src/components/filters/QasFilters.yml

- `QasFilters`: corrigido problema no método `updateValues`. O model interno de `filters` ficava desatualizado quando não tinha query na URL.
- `QasFilters`: corrigido problema na checagem se há valores nos `fields` retornados da API, caso não viesse `fields` ocorria um erro no console ao recuperar o tamanho do objeto de `fields`.
- `QasFilters`: corrigido atualização do model `currentFilters` que emitia o evento de atualização antes da query ser atualizada com base no filtro realizado.

QasFilters no filters in context fix

---

CHANGELOG.md
docs/src/examples/QasNestedFields/Basic.vue
docs/src/examples/QasNestedFields/ExSingleLabel.vue
docs/src/pages/components/nested-fields.md
ui/src/components/nested-fields/QasNestedFields.vue

- `QasNestedFields`: corrigido problemas referentes ao espaçamento do label quando é usado com `useSingleLabel`.

Fixed single label in QasNestedFields

---

CHANGELOG.md
docs/package-lock.json
docs/src/pages/start/develop.md
package-lock.json
ui/src/components/uploader/QasUploader.vue

- `QasUploader`: adicionado `QasEmptyResultText` para quando o modelValue do componente for vazio (também afeta o QasSignatureUploader).

Added QasEmptyResultText on QasUploader 

---

CHANGELOG.md
ui/src/components/date/QasDate.vue

`QasDate`: alterado a ordem de uso do método `resetEvents`, onde deverá limpar os eventos sempre, evitando problemas de manter antigos eventos quando deveriam serem limpados.

fix(QasDate): fix resetEvents function order

---

CHANGELOG.md
ui/src/components/label/QasLabel.vue
ui/src/css/components/field.scss

- `QasLabel`: modificado default da prop `margin` para `md (16px)`.
- `QasLabel`: modificado tipografia para `text-h4`.
- `ui/src/css/components/field.scss`: corrigido seletor de classe que estava deixando com cor no lugar errado.

Changes in QasLabel and field.scss

---

CHANGELOG.md
ui/src/helpers/rules.js

- Ajuste na validação do `required`

fix: rules validation

---

CHANGELOG.md
ui/src/components/box/QasBox.vue
ui/src/components/select-list/QasSelectList.vue

- `QasSelectList`: corrigido problema ao remover item do model quando `:emit-value="false"`.

Fixed QasSelectList

---

.vscode/settings.json
CHANGELOG.md
docs/src/examples/Delete/Basic.vue
docs/src/examples/Delete/DeleteWithRedirectRoute.vue
docs/src/examples/QasDelete/DeleteWithRedirectRoute.vue
docs/src/pages/components/delete.md
docs/src/pages/plugins/delete.md
docs/src/router/pages.js
ui/src/components/delete/QasDelete.vue
ui/src/components/delete/QasDelete.yml
ui/src/components/page-header/QasPageHeader.vue
ui/src/css/utils/container.scss
ui/src/plugins/delete/Delete.js
ui/src/plugins/delete/Delete.yml

- `Delete.js`: adicionado parâmetro `redirectRoute`, onde há a possibilidade de passar uma rota onde será redirecionado após deletar o item.
- `QasDelete`: adicionado props `redirectRoute` que será repassado para o plugin `Delete`.

feat(QasDelete): added redirect-route

---

CHANGELOG.md
ui/src/components/filters/QasFilters.vue

- `QasFilters`: Corrigido problema de merge entre os `fields` iniciais e a propriedade `fieldsProps` na computada `activeFilters`.
- `QasFilters`: Corrigido exibição vazia da badge de filtros ativos quando o valor não é encontrado na lista de opções de um campo de select.

QasFilters: some small fixes

---

.vscode/settings.json
CHANGELOG.md
ui/src/components/sortable/QasSortable.vue

- `QasSortable`: alterado watch da prop `list` para o deep, passando a ouvir quando dermos um `.push` ou `splice` no list.
- `QasSortable`: removido método `sort` dentro do watch `list` na qual estava ordenando a lista quando não deveria ser ordenando.

feat(QasSortable): fix watch list

---

CHANGELOG.md
ui/src/mixins/search-filter.js

- `search-filter`: adicionado validação da prop `useLazyLoading` no watch do `lazyLoadingProps.params` para não fazer request quando ela for false.

Changes in mixin search-filter.js

---

CHANGELOG.md
docs/src/examples/Dialog/Basic.vue
docs/src/examples/Dialog/DescriptionComponent.vue
docs/src/examples/Dialog/DialogWithDescriptionComponent.vue
docs/src/examples/QasDialog/DescriptionComponent.vue
docs/src/examples/QasDialog/DialogWithDescriptionComponent.vue
docs/src/pages/components/dialog.md
docs/src/pages/plugins/dialog.md
ui/src/components/dialog/QasDialog.vue
ui/src/components/label/QasLabel.yml
ui/src/plugins/delete/Delete.js

- `QasDialog`: possibilidade de passar a descrição como componente.
- `Delete.js`: merge do `dialogProps` vindo por parâmetro na função, com os valores defaults.

feat(QasDialog): added description component

---

CHANGELOG.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/dialog/QasDialog.vue

- `QasActionsMenu`: adicionado `@click.stop.prevent` solucionando o problema de utilizar o componente em conjunto com o `QasTableGenerator`.

feat(QasActionsMenu): added "@click.stop.prevent"

---

CHANGELOG.md
docs/src/pages/components/input.md
ui/src/components/date-time-input/QasDateTimeInput.vue
ui/src/components/input/QasInput.vue
ui/src/components/input/QasInput.yml
ui/src/components/numeric-input/QasNumericInput.vue
ui/src/components/search-input/QasSearchInput.vue

- `QasInput`: adicionado `inputmode` default de acordo com máscaras e type email.
- [`QasDateTimeInput`, `QasNumericInput`]: adicionado `inputmode="numeric"`.
- `QasSearchInput`: adicionado `inputmode="search"`.

added default inputmode values

---

CHANGELOG.md
ui/src/components/date-time-input/QasDateTimeInput.vue
ui/src/components/date-time-input/QasDateTimeInput.yml

- `QasDateTimeInput`: adicionado prop `datePopupProxyProps` para repassar props para o componente `QPopupProxy` do `QDate`.
- `QasDateTimeInput`: adicionado prop `timePopupProxyProps` para repassar props para o componente `QPopupProxy` do `QTime`.

feat: two new props DatePopupProxyProps e TimePopupProxyProps

---

CHANGELOG.md
ui/src/components/input/QasInput.vue

- `QasInput`: corrigido problema causado na versão `3.11.0-beta.14` onde o watch `mask` não foi alterado para `currentMask`.
- `QasInput`: removido computada `inputReference` que retornava o ref do `input`, pois seguindo a recomendação do Vue não é uma boa prática utilizar refs dentro de computadas, então foi movido a recuperação da ref para os métodos que à utilizam.
- `QasInput`: removido computada `hasError` pois não estava sendo utilizada em nenhum local no componente.

fix: QasInput mask watch

---

CHANGELOG.md
docs/src/pages/components/app-user.md
ui/src/components/app-user/QasAppUser.vue

- `QasAppUser`: modificado validação, agora se tiver pelo menos 1 opção, o select de vinculo é exibido.

Changes in QasAppUser

---

CHANGELOG.md
docs/src/examples/QasTextTruncate/WithCounter.vue
docs/src/pages/components/text-truncate.md
ui/src/components/text-truncate/QasTextTruncate.vue
ui/src/components/text-truncate/QasTextTruncate.yml

- `QasTextTruncate`: quebra visual por conta das alterações de estilos na fonte do texto, olhar todos lugares que utilizam o componente e caso necessário adaptar com as propriedades color e typography.
- `QasTextTruncate`: adicionado propriedades `color` e `typography` para controlar estilo da fonte.
- `QasTextTruncate` adicionado propriedades `useCounterMode`, `maxVisibleItem`, `list` e `useObjectList` para recurso de contador.

QasTextTruncate feature counter

---

CHANGELOG.md
ui/src/components/select-list-dialog/QasSelectListDialog.vue
ui/src/components/select-list-dialog/QasSelectListDialog.yml

- `QasSelectListDialog`: adicionado propriedade `useLazyLoading` para resolver problema quando usado com slot do `dialog-description`.

Fixed QasSelectListDialog

---

CHANGELOG.md
ui/src/components/select/QasSelect.vue

- `QasSelect`: corrigido watcher que não removida classe e mantinha opções desabilitadas quando deveria estar habilitada.

Fix QasSelect

---

.vscode/settings.json
CHANGELOG.md
docs/src/examples/QasAlert/Basic.vue
docs/src/examples/QasAlert/ExAlertError.vue
docs/src/examples/QasAlert/ExAlertModel.vue
docs/src/examples/QasAlert/ExAlertPersistent.vue
docs/src/pages/components/alert.md
ui/src/components/alert/QasAlert.vue
ui/src/components/alert/QasAlert.yml
ui/src/enums/Status.js

- `QasAlert`: removido propriedades [`color`, `title`].
- `QasAlert`: removido slot header.
- `QasNestedFields`: Adicionado suporte para função de callback na propriedade `disabled-rows`.
- `QasAlert`: adicionado novas propriedades [`status`, `storageKey`, `usePersistentModelOnClose`].
- `enums/Status`: adicionado novos enums para status.
- `QasAlert`: mudanças de layout e comportamento com componente.
- `QasAlert`: modificado componente para composition API.
- `QasAlert`: agora só é preciso passar um v-model caso realmente seja necessário.
- `QasAlert`: removido propriedades [`color`, `title`].
- `QasAlert`: removido slot header.

Changes in QasAlert

---

CHANGELOG.md
app-extension/src/boot/query-cache.js
docs/src/pages/boot/query-cache.md

- `boot/query-cache.js`: modificado o valor padrão do `useCache`, antes todas rotas por default era `true`, agora, apenas rotas que contém a chave `name` e o name termine com a string `list` ou `List` terão `true` como padrão.
- `boot/query-cache.js`: modificado o valor padrão do `useCache`, antes todas rotas por default era `true`, agora, apenas rotas que contém a chave `name` e o name termine com a string `list` ou `List` terão `true` como padrão.

Update useCache default

---

CHANGELOG.md
app-extension/src/boot/query-cache.js

- `boot/query-cache.js`: adicionado optional chaining to route name.

Added optional chaining

---

CHANGELOG.md
docs/src/examples/QasDialog/ExDialogCancelAndOk.vue
docs/src/pages/components/dialog.md
ui/src/components/app-user/QasAppUser.vue
ui/src/components/dialog/QasDialog.vue
ui/src/components/dialog/QasDialog.yml

- `QasDialog`: adicionado novos eventos `@cancel` que dispara toda vez que é clicado no botão "cancel".
- `QasDialog`: corrigido bug que fazia que pagina recarregasse ao dar enter quando a prop useForm tinha o valor "true".
- `QasDialog`: agora a seção de `actions` foi movida para dentro do QForm, isto faz com que ao clicar enter, o botão deja disparado mesmo que não tenha sido clicado (quando useForm for true).

QasDialog changes

---

CHANGELOG.md
ui/src/components/dialog/QasDialog.vue
ui/src/components/infinite-scroll/QasInfiniteScroll.vue

- `QasInfiniteScroll`: corrigido problema do componente não resetar ao utilizar o método `refresh` em alguns cenários.

fix: infinite scroll

---

CHANGELOG.md
docs/src/examples/QasAppBar/Basic.vue
docs/src/examples/QasAppMenu/Basic.vue
docs/src/examples/QasAppUser/Basic.vue
docs/src/examples/QasLayout/Basic.vue
docs/src/pages/components/app-user.md
ui/src/components/app-user/QasAppUser.vue
ui/src/components/app-user/QasAppUser.yml

- `QasAppUser`: removido propriedades `companiesOptions` e `currentCompany` em favor de utilizar a nova propriedade `companyProps`.
- `QasAppUser`: adicionado nova propriedade `companyProps` que repassa todas as props para o select de vínculos.
- `QasAppUser`: removido propriedades `companiesOptions` e `currentCompany` em favor de utilizar a nova propriedade `companyProps`.

QasAppUser Changes

---

CHANGELOG.md
ui/src/css/plugins/notify.scss
ui/src/plugins/notify-error/NotifyError.js
ui/src/plugins/notify-success/NotifySuccess.js
ui/src/shared/notify-config.js

- `Notify`: alterado notify para aplicar estilos nos actions somente em NotifySuccess e NotifyError,
uma vez que da forma anterior esta afetando todos os casos.

Notify changes

---

CHANGELOG.md
docs/src/examples/QasUploader/ExUploaderCardCallback.vue
docs/src/pages/components/uploader.md
ui/src/components/gallery-card/QasGalleryCard.vue
ui/src/components/gallery-card/QasGalleryCard.yml
ui/src/components/uploader/QasUploader.vue
ui/src/components/uploader/private/PvUploaderGalleryCard.vue

- `QasGalleryCard`: adicionado novas propriedades `errorMessage` e `errorIcon` para controlar conteúdo quando dar falha ao carregar imagem.
- `QasGalleryCard`: adicionado novo slot `image-error-icon` para controle de ícone.
- `QasUploader`: propriedade `galleryCardProps` agora aceita callback function, para ter controle personalizado por card.
- `QasGalleryCard`: modificado estilo de card para erro.

Changes in QasUploader and QasGalleryCard

---

CHANGELOG.md
docs/src/pages/components/form-view.md
ui/src/components/app-user/QasAppUser.vue
ui/src/components/app-user/QasAppUser.yml
ui/src/components/form-view/QasFormView.vue
ui/src/components/form-view/QasFormView.yml

- `QasAppUser`: alterado `dataCy` para `data-cy`.
- `QasFormView`: adicionado nova propriedade `useNotifySuccess` para controlar quando mostrar a notificação de sucesso (utilizar somente em casos muito específicos, olhar documentação).
- `QasAppUser`: alterado `dataCy` para `data-cy`.

Changes in QasFormView and QasAppUser

---

CHANGELOG.md
ui/src/components/actions/QasActions.vue
ui/src/enums/Align.js

Composition API
- `enums/Align`: adicionado novo enum `FlexAlign` para alinhamentos.
- `QasActions`: corrigido computada `defaultGutter` que sempre retornava `md` ou `lg`, ignorando a prop `gutter`.
- `QasActions`: Alterado componente para Composition API.

Fix gutter issue and update QasActions to Composition API

---

CHANGELOG.md
ui/src/components/actions-menu/QasActionsMenu.vue

- `QasActionsMenu`: alterado componente para Composition API.

Refactor QasActionsMenu component to Composition API

---

CHANGELOG.md
ui/src/components/dialog/QasDialog.vue
ui/src/plugins/dialog/Dialog.js

- `QasDialog`: corrigido problema de não emitir o evento `@hide`.
- `plugins/Dialog.js`: corrigido problema de não retornar a instância do dialog.

Fix issues with QasDialog and plugins/Dialog.js

---

CHANGELOG.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/actions-menu/QasActionsMenu.yml
ui/src/components/nested-fields/QasNestedFields.vue
ui/src/components/nested-fields/QasNestedFields.yml

- [`QasNestedFields`, `QasActionsMenu`]: adicionado novos seletores `data-cy` no componente.

New data cy

---

CHANGELOG.md
ui/src/components/table-generator/QasTableGenerator.vue
ui/src/pages/ErrorComponent.vue

- `QasTableGenerator`: alterado hover da cor de fundo da linha da tabela para a cor de background padrão.
- `ErrorComponent`: corrigido problema na exibição da cor de fundo.

QasTableGenerator new bg hover color and fix ErrorComponent background-color

---

CHANGELOG.md
docs/src/examples/QasAppUser/Basic.vue
ui/src/components/app-user/QasAppUser.vue

- `QasAppUSer`: corrigido select de empresa quando o select possuía busca, que ao clicar no botão de limpar, não limpava e ainda tentava alterar o vinculo para um vinculo vazio.

Fixed QasAppUser

---

CHANGELOG.md
ui/src/components/card/QasCard.vue

- `QasBtnDropdown`: alterado componente para Composition API.

Refactor QasCard to Composition API

---

CHANGELOG.md
ui/src/components/debugger/QasDebugger.vue

- `QasDebugger`: alterado componente para Composition API.

Refactor QasDebugger to Composition API

---

CHANGELOG.md
ui/src/components/empty-result-text/QasEmptyResultText.vue

- `QasDialogRouter`: alterado componente para Composition API.

Refactor QasEmptyResultText to Composition API

---

CHANGELOG.md
ui/src/components/label/QasLabel.vue

- `QasLabel`: alterado componente para Composition API.

Refactor QasLabel to Composition API

---

CHANGELOG.md
ui/src/components/checkbox-group/QasCheckboxGroup.vue

- `QasCheckboxGroup`: alterado componente para Composition API.

Refactor QasCheckboxGroup to Composition API

---

CHANGELOG.md
ui/src/components/gallery-card/QasGalleryCard.vue

- `QasGalleryCard`: alterado componente para Composition API.

Refactor QasGalleryCard to Composition API

---

CHANGELOG.md
ui/src/components/gallery/QasGallery.vue
ui/src/components/gallery/composables/use-delete.js
ui/src/components/gallery/private/PvGalleryCarouselDialog.vue
ui/src/components/gallery/private/PvGalleryDeleteDialog.vue
ui/src/vue-plugin.js

- `QasGallery`: alterado componente para Composition API.
- `/ui/src/vue-plugin.js`: adicionado método `getAction` do `@bildvitta/store-adapter` na variável global `qas` para conseguir utiliza-lo no composition API (NÃO UTILIZAR NO PROJETO).

Refactor QasGallery to Composition API

---

CHANGELOG.md
ui/src/components/tabs-generator/QasTabsGenerator.vue

- `QasTabsGenerator`: alterado componente para Composition API.

Refactor QasTabsGenerator to Composition API

---

CHANGELOG.md
ui/src/components/dialog-router/QasDialogRouter.vue

- `QasDialogRouter`: alterado componente para Composition API.

Refactor QasDialogRouter to Composition API

---

CHANGELOG.md
ui/src/components/delete/QasDelete.vue

- `QasDelete`: alterado componente para Composition API.

Refactor QasDelete to Compositon API

---

CHANGELOG.md
docs/src/examples/QasDate/ExDateEvents.vue
ui/src/components/date/QasDate.vue
ui/src/components/date/QasDate.yml
ui/src/components/date/enums/DateMaskOptions.js

- `QasDate`: alterado componente para Composition API.
- `QasDate`: removido propriedade `useUnmaskEvents`, uma vez que ela não era utilizada para nada dentro do componente.

Refactor QasDate to Composition API

---

CHANGELOG.md
ui/src/components/date-time-input/QasDateTimeInput.vue

- `QasDateTimeInput`: alterado componente para Composition API.
- `QasDateTimeInput`: removido métodos blur e focus que não estavam sendo utilizados.

Refactor QasDateTimeInput to Composition API

---

CHANGELOG.md
ui/src/components/actions-menu/QasActionsMenu.vue

- `QasActionsMenu`: Corrigido problema da const `hasDelete` do composable `useDelete`, onde não estava reativo pois não foi feito como computada.

Fix issue in QasActionsMenu

---

CHANGELOG.md
ui/src/components/alert/QasAlert.vue
ui/src/components/app-bar/QasAppBar.vue
ui/src/components/app-menu/QasAppMenu.vue
ui/src/components/app-menu/private/PvAppMenuDropdown.vue
ui/src/components/app-user/QasAppUser.vue
ui/src/components/avatar/QasAvatar.vue
ui/src/components/breakline/QasBreakline.vue
ui/src/components/btn-dropdown/QasBtnDropdown.vue
ui/src/components/checkbox-group/QasCheckboxGroup.vue
ui/src/components/date-time-input/QasDateTimeInput.vue
ui/src/components/date/QasDate.vue
ui/src/components/delete/QasDelete.vue
ui/src/components/dialog-router/QasDialogRouter.vue
ui/src/components/dialog/QasDialog.vue
ui/src/components/dialog/composables/use-cancel.js
ui/src/components/dialog/composables/use-dynamic-components.js
ui/src/components/dialog/composables/use-ok.js
ui/src/components/form-generator/QasFormGenerator.vue
ui/src/components/gallery/QasGallery.vue
ui/src/components/grid-generator/QasGridGenerator.vue
ui/src/components/infinite-scroll/QasInfiniteScroll.vue
ui/src/components/select-list-dialog/QasSelectListDialog.vue
ui/src/components/timeline/QasTimeline.vue
ui/src/composables/private/use-generator.js

- `QasActionsMenu`: Corrigido problema da const `hasDelete` do composable `useDelete`, onde não estava reativo pois não foi feito como computada.
- Adicionado prefixo de `props` nas propriedades dentro do template:
- QasAppAlert: [text].
- QasAppBar: [brand, title].
- QasAppMenu: [items, title].
- QasAppUser: [users, notifications].
- QasAvatar: [image, icon, title].
- QasBreakline: [tag, icon, title].
- QasDialog: [card, persistent, useForm].
- QasFormGenerator: [fieldsProps, modelValue, errors].
- QasGridGenerator: [headerClass, contentClass].
- QasTimeline: [list].
- Modificado nome `emits` para `emit` no script setup:
- QasAppBar.
- QasAppMenu.
- QasAppUser.
- QasBtnDropdown.
- Modificado $attrs para useAttrs() no template:
- QasBreakline.
- QasDialog.
- Modificado slots para …

Refactor Composition Components

---

CHANGELOG.md
docs/src/examples/QasDrawer/Basic.vue
ui/src/components/drawer/QasDrawer.vue
ui/src/components/drawer/QasDrawer.yml
ui/src/components/layout/private/PvLayoutNotificationsDrawer.vue

- `QasDrawer`: loading estava quebrando no mobile.
- `QasDrawer`: adicionado default `60%` na propriedade `maxWidth`.

Fixed maxWidth prop

---

CHANGELOG.md
ui/src/components/list-items/QasListItems.vue

- `QasListItens`:
- alterado cor do botão de `primary` para `grey-10`.
- alterado espaçamento entre itens de `lg` para `md`.
- removido `v-ripple` para se adequar ao design.

Changes in QasListItens

---

CHANGELOG.md
ui/src/components/grabbable/QasGrabbable.vue
ui/src/helpers/set-scroll-on-grab.js

- `QasGrabbable`:
- corrigido problema do conteúdo ser alterado após o componente ser montado e o grab não ser ajustado de acordo com o novo conteúdo.
- corrigido z-index do fade lateral.

fix: QasGrabbable

---

CHANGELOG.md
docs/src/pages/components/option-group.md
ui/src/components/option-group/QasOptionGroup.vue

- `QasOptionGroup`: alterado componente para sobrescrever a prop `inline`.

Changes in QasOptionGroup

---

CHANGELOG.md
docs/src/examples/QasBoardGenerator/Basic.vue
docs/src/pages/components/board-generator.md
ui/src/components/board-generator/QasBoardGenerator.vue
ui/src/components/board-generator/QasBoardGenerator.yml

- `QasBoardGenerator`: 
- alterado prop `results` para `headers`.
- `v-model` agora é recuperado pelo `v-model:results`.
- alterado prop `use-shallow-ref` para `use-mark-raw`.
- `QasBoardGenerator`: Adicionado eventos `fetch-columns-success`, `fetch-columns-error`, `fetch-column-success` e `fetch-column-error`.

feat: created results model/fields slot

---

CHANGELOG.md
ui/src/components/app-menu/QasAppMenu.vue

- `QasAppMenu`: Corrigido bug que ocorria com o QDrawer quando usado com a versão do vue `v3.4+`, onde era removido o scroll da pagina quando ocorria um resize na pagina de desktop pra mobile.

QasAppMenu: fixed issue on resize.

---

CHANGELOG.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/actions-menu/composables/use-options-actions.js

- `QasActionsMenu`: Corrigido props defaults que estavam faltando no componente após a refatoração/redesign (`{ useHoverOnWhiteColor: true, useLabelOnSmallScreen: false }`).

QasActionsMenu: fixed default props

---

CHANGELOG.md
docs/src/examples/QasFormGenerator/ExFormCommonColumns.vue
docs/src/examples/QasGridGenerator/Basic.vue
docs/src/examples/QasGridGenerator/ExGridCommonColumns.vue
docs/src/pages/components/form-generator.md
docs/src/pages/components/grid-generator.md
ui/src/components/form-generator/QasFormGenerator.yml
ui/src/components/grid-generator/QasGridGenerator.yml
ui/src/composables/private/use-generator.js

- [`QasFormGenerator`, `QasGridGenerator`]: removido a propriedade `useCommonColumns` em favor de utilizar a propriedade `commonColumns`.
- [`QasFormGenerator`, `QasGridGenerator`]: adicionado nova propriedade `commonColumns`, esta propriedade vai substituir a necessidade do `useCommonColumns` e dar mais flexibilidade.
- [`QasFormGenerator`, `QasGridGenerator`]: removido a propriedade `useCommonColumns` em favor de utilizar a propriedade `commonColumns`.

QasGridGenerator and QasFormGenerator: added commonColumns

---

CHANGELOG.md
docs/src/pages/components/expansion-item.md
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/toggle-visibility/QasToggleVisibility.vue

- `QasExpansionItem`:
- Repassando todos eventos do QExpansionItem.
- Mudanças de layout quando usado expansion dentro de expansion.
- `QasToggleVisibility`: adicionado evento `prevent.stop` no botão para não disparar evento de click na tabela.

QasExpansionItem and QasToggleVisibility changes.

---

CHANGELOG.md
docs/src/examples/QasTableGenerator/NoBox.vue
docs/src/pages/components/table-generator.md
ui/src/components/table-generator/QasTableGenerator.vue
ui/src/components/table-generator/QasTableGenerator.yml

- `QasTableGenerator`: adicionado nova propriedade `useBox`.

QasTableGenerator changes

---

CHANGELOG.md
docs/src/examples/QasExpansionItem/Basic.vue
docs/src/pages/components/expansion-item.md
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/expansion-item/QasExpansionItem.yml

- `QasExpansionItem`: Adicionado nova propriedade `useHeaderSeparator` para forçar o controle do QSeparator.
- `QasExpansionItem`: Adicionado classe para z-index, onde corrige o problema de quando usado grid com gutter no conteúdo e sobrepunha o header fazendo com que perdesse o evento de click.

QasExpansionItem changes.

---

CHANGELOG.md
docs/src/examples/QasFormGenerator/Fieldset.vue
docs/src/pages/components/form-generator.md
ui/src/components/form-generator/QasFormGenerator.vue
ui/src/components/header/QasHeader.vue

- `QasFormGenerator`: Agora o fieldset implementa o componente `QasHeader`.
- `QasHeader`: modificado espaçamento bottom padrão de `xl` para `md`.

Changes in QasFormGenerator and QasHeader

---

CHANGELOG.md
docs/src/examples/QasExpansionItem/WithBox.vue
docs/src/pages/components/expansion-item.md
ui/src/components/btn-dropdown/QasBtnDropdown.vue
ui/src/components/date-time-input/QasDateTimeInput.vue
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/grid-generator/QasGridGenerator.vue
ui/src/components/table-generator/QasTableGenerator.vue

- `QasTableGenerator`: adicionado componente `QasEmptyResultText` onde será exibido no caso dos valores da tabela serem vazios.
- `QasActionsMenu`: adicionado label `Opções` no botão splitted quando não for mobile.
- `QasExpansionItem`: modificado componente para ter uma borda caso esteja dentro de um `QasBox`.
- `QasDateTimeInput`: alterado o ícone do calendário.

Changes QasTableGenerator, QasActionsMenu, QasExpansionItem, QasDateTimeInput

---

CHANGELOG.md
docs/src/examples/QasFormGenerator/WithButton.vue
ui/src/components/form-generator/QasFormGenerator.vue
ui/src/components/grid-generator/QasGridGenerator.vue
ui/src/components/list-view/QasListView.vue
ui/src/components/text-truncate/QasTextTruncate.vue

- `QasListView`: modificado a forma que os loadings são exibidos.
- `QasFormGenerator`: ajuste ao usar o `buttonProps` com um select com opções com label grande, fazia com que o select não respeitasse o ellipsis.

feat: fix form-generator button / list-view loading

---

CHANGELOG.md
docs/src/examples/QasExpansionItem/Disable.vue
docs/src/examples/QasExpansionItem/Group.vue
docs/src/pages/components/expansion-item.md
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/expansion-item/QasExpansionItem.yml

- `QasExpansionItems`: modificado slot header, agora ao abrir, ele sobrescreve toda a seção header, incluindo o botão de dropdown.
- `QasExpansionItems`:
- adicionado propriedade `disable`.
- adicionado propriedade `disableButton`.
- adicionado propriedade `group`.
- adicionado v-model.
- adicionado novo slot `header-left`.
- `QasExpansionItems`: modificado slot header, agora ao abrir, ele sobrescreve toda a seção header, incluindo o botão de dropdown.

QasExpansionItems changes

---

CHANGELOG.md
ui/src/components/header/QasHeader.vue

- `QasHeader`: corrigido bug quando abria o slot de actions e não renderizava elemento, por exemplo com v-if.

QasHeader: fix actions slot.

---

CHANGELOG.md
ui/src/components/expansion-item/QasExpansionItem.vue

…undefined
- `QasExpansionItem`: corrigido propriedade "group" que o default era string vazia, e isto fazia que todos fizessem parte do mesmo grupo de `""`.

QasExpansionItem: fix grouping defaults

---

CHANGELOG.md
ui/src/components/chart-view/QasChartView.vue

- `QasChartView`: corrigido hook `unmounted` para `beforeUnmounted`, quando saia de uma pagina com chart e ia para outra, o componente removia o registro após o registro da outra pagina, gerando erros.

Hotfix: QasChartView unregister issue.

---

CHANGELOG.md
docs/src/examples/QasCheckbox/Children.vue
docs/src/examples/QasCheckbox/Options.vue
docs/src/examples/QasExpansionItem/WithMaxContentHeight.vue
docs/src/examples/QasField/Checkbox.vue
docs/src/examples/QasRadio/OptionGroup.vue
docs/src/pages/components/checkbox.md
docs/src/pages/components/expansion-item.md
ui/src/components/checkbox/QasCheckbox.vue
ui/src/components/checkbox/QasCheckbox.yml
ui/src/components/copy/QasCopy.vue
ui/src/components/copy/QasCopy.yml
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/expansion-item/QasExpansionItem.yml
ui/src/components/radio/QasRadio.vue
ui/src/components/radio/QasRadio.yml
ui/src/components/table-generator/QasTableGenerator.vue
ui/src/helpers/set-scroll-on-grab.js

ExpansionItem
Correção TableGenerator
DEPOIS:
ANTES:

Ajustes - QasExpansionItem / QasCheckbox / QasRadio / QasTableGenerator / QasGrabbable / QasCopy

---

CHANGELOG.md
docs/src/examples/QasExpansionItem/HeaderLeftSlot.vue
docs/src/examples/QasExpansionItem/HeaderSlot.vue
docs/src/pages/components/expansion-item.md
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/expansion-item/QasExpansionItem.yml

feat(QasExpansionItem): HeaderSlot full width

---

CHANGELOG.md
docs/src/examples/QasExpansionItem/WithBox.vue
ui/src/components/expansion-item/QasExpansionItem.vue

feat(QasExpansionItem): insert border negative when has error

---

CHANGELOG.md
ui/src/components/card/QasCard.vue

- `QasCard`: a prop `actionsMenuProps` anteriormente era passado diretamente era repassado pra o `list` internamente, impedindo de repassar outras props. Agora deve passar o `list` dentro do `actionsMenuProps`.
- `QasCard`: Modificado a forma de passar `actionsMenuProps`, agora é possível passar outras props além do `list`.

feat: actionsMenuProps card

---

CHANGELOG.md
docs/src/pages/components/app-menu.md
ui/src/components/app-menu/QasAppMenu.vue

- `QasAppMenu`: corrigido problema que ocorria quando um item do menu com "children" ficava vazio, ele quebrava por não encontrar a rota e mostrava um label mesmo que sem nenhum item abaixo.

QasAppMenu: fix children issue.

---

CHANGELOG.md
docs/src/examples/QasCopy/WithRawText.vue
docs/src/pages/components/copy.md
ui/src/components/copy/QasCopy.vue
ui/src/components/copy/QasCopy.yml

- `QasCopy`: adicionado prop `raw-text` pra usar em casos onde o texto exibido não é o mesmo do valor que vai ser copiado.

feat: added raw-text

---

CHANGELOG.md
docs/src/examples/QasFormGenerator/Fieldset.vue
ui/src/components/form-generator/QasFormGenerator.vue

- `QasFormGenerator`: corrigido validação para exibição do `fieldset`, ao não passar propriedades como label e description, fazia com que ficasse um espaço em branco.

feat: fix header fieldset

---

CHANGELOG.md
docs/src/pages/components/board-generator.md
ui/src/components/board-generator/QasBoardGenerator.vue
ui/src/components/board-generator/QasBoardGenerator.yml

- `QasBoardGenerator`:
- adicionado nova propriedade `beforeUpdatePosition`.
- adicionado novo evento `update-error`.
- adicionado payload do retorno da api no evento `update-success`.
- adicionado método `cancelDrop` no `defineExpose`.

QasBoardGeneratorChanges

---

CHANGELOG.md
docs/src/pages/components/expansion-item.md
ui/src/components/expansion-item/QasExpansionItem.vue
ui/src/components/expansion-item/QasExpansionItem.yml

- `QasExpansionItem`: a prop `useHeaderSeparator` foi removida, agora não existe mais separator no header.
- `QasExpansionItem`: 
- Modificado a borda do componente, agora ao ter um expansion dentro de outro expansion, ficará uma borda.
- `QasExpansionItem`: a prop `useHeaderSeparator` foi removida, agora não existe mais separator no header.

feat: added expansion border

---

CHANGELOG.md
ui/src/components/expansion-item/QasExpansionItem.vue

- `QasExpansionItem`: corrigido ícone de dropdown quando possui um expansion dentro de outro.

feat: fix dropdown icon

---

CHANGELOG.md
docs/src/examples/QasTextTruncate/WithBadge.vue
docs/src/pages/components/text-truncate.md
ui/src/components/badge/QasBadge.vue
ui/src/components/form-generator/QasFormGenerator.yml
ui/src/components/grid-generator/QasGridGenerator.vue
ui/src/components/grid-generator/QasGridGenerator.yml
ui/src/components/grid-item/QasGridItem.vue
ui/src/components/text-truncate/QasTextTruncate.vue
ui/src/components/text-truncate/QasTextTruncate.yml
ui/src/composables/private/use-generator.js
ui/src/shared/badge-config.js

`QasTextTruncate`: Adicionado novas propriedade `useBadge` e `useWrapBadge`.
- `QasGridGenerator`: modificado espaçamento entre itens no dialog para `sm`.
- `QasGridItem`: modificado classe de cor, agora o label tem as mesmas cores tanto inline quando modo normal "text-grey-10".
- `QasGridGenerator`:
- modificado tamanho default da propriedade "gutter", agora quando for "useInline" terá o default de "8px".
- `composables/private/useGenerator`: modificações referente ao gutter para o QasGridGenerator.
- corrigido typo "getContainerClassses" por "getContainerClasses".

Changes in QasGridGenerator and QasTextTruncate

---

CHANGELOG.md
ui/src/components/table-generator/QasTableGenerator.vue

- `QasTableGenerator`: corrigido hover da linha onde que no Safari pegava a tabela toda ao invés da própria linha.

fix(QasTableGenerator): fix hover

---

CHANGELOG.md
docs/src/examples/QasActionsMenu/ExWithLoading.vue
docs/src/examples/QasBtn/ExWithLoading.vue
docs/src/pages/components/actions-menu.md
docs/src/pages/components/button.md
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/btn-dropdown/QasBtnDropdown.vue
ui/src/components/btn-dropdown/QasBtnDropdown.yml
ui/src/components/btn/QasBtn.vue
ui/src/css/components/button.scss
ui/src/css/mixins/set-button.scss

- `QasActionsMenu`: corrigido exibição de loading no componente dentro do dropdown ao ter uma prop `loading: true`.

feat: fix actions menu loading

---

CHANGELOG.md
ui/src/components/list-view/QasListView.vue
ui/src/components/list-view/QasListView.yml
ui/src/mixins/view.js

- `QasListView`: Adicionado propriedade `use-store` para dar a possibilidade de utilizar o componente sem a store do vuex/pinia.

`QasListView`: Adicionado propriedade use-store para controlar quando utilizar store

---

CHANGELOG.md
ui/src/components/layout/private/PvLayoutNotificationCard.vue
ui/src/helpers/filters.js

- `dateTime | PvLayoutNotificationCard`: Alterado padrão de data para `"dd/MM/yyyy 'às' HH:mm:ss"` para melhorar a legibilidade.
closes #1294 

Alterado token padrão do dateTime para ter `às` entre as date / horário

---

CHANGELOG.md
docs/src/examples/QasCard/InsideDialog.vue
docs/src/pages/components/card.md
ui/src/components/card/QasCard.vue

- `QasCard`: Modificado estilo do card para utilizar bordas ao invés de box quando estiver dentro de um `QasDialog`.
Closes #1289

`QasCard`: Alterado para ter bordas quando estiver dentro de um dialog

---

CHANGELOG.md
docs/src/examples/QasAlert/InsideDialog.vue
docs/src/pages/components/alert.md
ui/src/components/alert/QasAlert.vue

- `QasAlert`: Modificado comportamento para não ter box quando estivar dentro de um `QasDialog`.
Closes #1288  

`QasAlert`: Modificado comportamento para não ter box quando estivar dentro de um dialog

---

CHANGELOG.md
docs/src/examples/QasCard/Basic.vue
docs/src/examples/QasInput/Textarea.vue
ui/src/components/actions-menu/QasActionsMenu.vue
ui/src/components/reports-filters/QasReportsFilters.vue

- `QasActionsMenu`: corrigido alinhamento quando está dentro de outro container, como por exemplo o `QasPageHeader`. [[#1337](https://github.com/bildvitta/asteroid/issues/1337)]
- `QasReportsFilters`: corrigido imports dos componentes internos.

feat: fix reports-filters/actions-menu

---

CHANGELOG.md
docs/src/examples/QasStepper/StepperWithError.vue
docs/src/examples/QasStepper/Vertical.vue
docs/src/pages/components/stepper.md
ui/src/components/stepper/QasStepper.vue
ui/src/components/stepper/QasStepper.yml

- `QasStepper`: Adicionado prop `useVertical` para ter possibilidade de utilizá-lo na vertical.
- `QasStepper`: Modificado exibição da cor primária nas linhas de cada step.

`QasStepper`: Opção para uso na vertical e ajustes na exibição das linhas de done/active (padronizado DS)

---

CHANGELOG.md
ui/src/components/numeric-input/QasNumericInput.vue
ui/src/css/components/item.scss

- `QasSelect`: Corrigido cor de foco nas opções durante a navegação com teclado (teclas de seta para cima/baixo).
- `QasNumericInput`: Corrigido foco do campo, pois quando utilizado via tab, o campo não focava.

`QasSelect | item.scss`: Corrigido cor de foco na opção quando utilizado teclado

---

CHANGELOG.md
docs/src/pages/components/form-generator.md
ui/src/composables/private/use-generator.js

- `QasFormGenerator`: corrigido comportamento quando `fields` está vazio, agora não exibe nenhum campo ao invés de exibir todos os campos disponíveis.

`QasFormGenerator`: corrigido comportamento quando `fields` está vazio, agora não exibe nenhum campo ao invés de exibir todos os campos disponíveis.

---

CHANGELOG.md
docs/src/examples/QasAlert/MultipleButtons.vue
docs/src/pages/components/alert.md
ui/src/components/alert/QasAlert.vue
ui/src/components/alert/QasAlert.yml

- `QasAlert`: Adicionado possibilidade do componente ter vários `QasBtn` ou `RouterLink`.

`QasAlert`: Adicionado possibilidade de ter multiplos botoes e links
